issue-96 add user data conversion to dailyOrder
Qmannn/food-service pull request #100
Opened 2019-05-20 15:17 UTC by ondrosru

2019-05-24 18:18 UTC, Qmannn requested changes

2019-05-24 18:18 UTC, Qmannn commented on FoodService/Domain/Services/ConvertToDailyOrder/ConvertToDailyOrder.cs
> +namespace FoodService.Domain.Services.ConvertToDailyOrder
Папку ConvertToDailyOrder давай переименуем в Converters (папка в которой будут лежать все сервисы типа Конвертер) так структура папок будет более гибкой

2019-05-24 18:18 UTC, Qmannn commented on FoodService/Domain/Services/ConvertToDailyOrder/ConvertToDailyOrder.cs
> +    public class ConvertToDailyOrder: IConvertToDailyOrder
ConvertToDailyOrder больше подходит для названия метода (что делается). Класс, думаю, лучше называть так, как называется тот "кто делает". В данном случае класс конвертирует dailyOrder, поэтому лучше выбрать название DailyOrderConverter.
Предлагаю переименовать

2019-05-24 18:18 UTC, Qmannn commented on FoodService/Domain/Services/ConvertToDailyOrder/ConvertToDailyOrder.cs
> +            Menu menu = _menuRepository.GetMenu(order.MenuId);
Сервис типа Converter должен иметь минимальное количество обязанностей, а именно только конвертировать что-то во что-то, получение данных из репозитория лучше разместить уровнем выше, а в этот метод передавать уже все необходимые данные для конвертации снаружи.
то есть в параметрах будут передаваться 
`public DailyOrder ConvertOrderToDailyOrder(OrderDto order, Menu menu, User user)`

2019-05-24 18:18 UTC, Qmannn commented on FoodService/Domain/Services/ConvertToDailyOrder/ConvertToDailyOrder.cs
> +            UserDto user = _usersService.GetUser(order.UserId);
_usersService - он выдает нам данные для передачи на фронтенд, то есть Dto, использовать Dto как источник данных во внутренних сервисах может привести к невозможности в дальнейшем модифицировать контракты с фронтендом.
Давай будем использовать User - класс представляющий таблицу в базе.

Ну и еще хорошо бы учесть комментарий выше и передать User через параметры метода. (в конвертер лучше никаких сервисов, кроме других конвертеров, если они нужны, передавать не нужно)

2019-05-24 18:18 UTC, Qmannn commented on FoodService/Domain/Services/ConvertToDailyOrder/ConvertToDailyOrder.cs
> +                if (menu.MenuDishes.ToList().Find(item => item.DishId == dish.Id) != null)
Давай немного оптимизируем.
Есть такая структура данных - Dictionary, он же словарь, он позволяет по некоторому ключу обратиться к объекту, которые лежит в значении по самому ключу
например:
{1: "one"}
{2: "two"}

В таком случае обращение к значению по ключу будет очень быстрым за счет того, что словарь использует Hash таблицы (возможно расскажу как нибудь или можно погуглить, в них используются наиболее оптимальные алгоритмы поиска).

Структура данных HashSet нечто похожее - это массив уникальных значений, данные в котором расположены случайно, но поиск по HashSet происходит быстро, поэтому можно без проблем в большом объеме даннх проверить наличие элемента.
например:
`HashSet<int> set = new HashSet<int>(new []{1,1,1,2,3,5,5,5,4});`
Выше описал создание hashSet для объектов типа Int.
Как видно, в констуктор передан массив неуникальных числе, однако сет хранит только уникальные значения, следовательно после создания у нас в HashSet будет только 4 значения
1,2,3,5,4
Если выполним операцию set.Add(5) - то опять же количество элементов в наборе не изменится, поскольку значение 5 уже есть.

Преимущество HashSet так же в том, что поиск по нему производится быстро(на большом количестве данных по сравнению с поиском в List)

Так, например, операция
`set.Contains(5)` выполнится быстро, поэтому лучше для таких операция использовать HashSet

**С этой штукой есть нюансы, связанные с тем, что на маленьком объеме данных List все таки быстрее, но по этому поводу можно погуглить отдлеьно**

_P.s. В примере выше, List отработает быстрее, но чтобы попробовать советую заиспользовать все таки HashSet_


В данном случае предлагаю код сделать таким:
```
            convertedOrder.Dishes = new List<DailyOrderDish>();
            HashSet<int> existingDishIds = new HashSet<int>(menu.MenuDishes.Select(item => item.DishId));

            foreach (DishDto dish in order.OrderDishes)
            {
                if (existingDishIds.Contains(dish.Id))
                {
                    DailyOrderDish dailyDish = ConvertOrderDish(dish);
                    convertedOrder.Dishes.Add(dailyDish);
                }
            }
            return convertedOrder;
```

2019-05-24 18:18 UTC, Qmannn commented on FoodService/Controllers/OrderController.cs
> +            _convertToDailyOrder.ConvertOrderToDailyOrder(order);
Можно добавить сервис OrderBuilder, где как раз вместо конвертера достать из базы Menu и User, а затем вызвать Converter.

Новый класс надо положить в папку Builders, которая в свою очередь будет лежать в папке Services

2019-05-27 10:08 UTC, ondrosru commented on FoodService/Domain/Services/ConvertToDailyOrder/ConvertToDailyOrder.cs
> +namespace FoodService.Domain.Services.ConvertToDailyOrder
сделал

2019-05-27 10:11 UTC, ondrosru commented on FoodService/Domain/Services/ConvertToDailyOrder/ConvertToDailyOrder.cs
> +    public class ConvertToDailyOrder: IConvertToDailyOrder
сделал

2019-05-27 10:11 UTC, ondrosru commented on FoodService/Domain/Services/ConvertToDailyOrder/ConvertToDailyOrder.cs
> +            Menu menu = _menuRepository.GetMenu(order.MenuId);
сделал

2019-05-27 10:15 UTC, ondrosru commented on FoodService/Domain/Services/ConvertToDailyOrder/ConvertToDailyOrder.cs
> +            UserDto user = _usersService.GetUser(order.UserId);
сделал

2019-05-27 10:16 UTC, ondrosru commented on FoodService/Domain/Services/ConvertToDailyOrder/ConvertToDailyOrder.cs
> +                if (menu.MenuDishes.ToList().Find(item => item.DishId == dish.Id) != null)
сделал

2019-05-27 10:16 UTC, ondrosru commented on FoodService/Controllers/OrderController.cs
> +            _convertToDailyOrder.ConvertOrderToDailyOrder(order);
сделал

2019-06-03 14:40 UTC, Qmannn approved these changes

2019-06-03 14:40 UTC, merged