Добавлено получение меню из базы в FoodService
Qmannn/food-service pull request #105
Opened 2019-06-03 15:54 UTC by ondrosru

2019-06-03 21:23 UTC, Qmannn requested changes

2019-06-03 21:23 UTC, Qmannn commented on FoodService/Domain/Services/Finders/DailyMenuFinder.cs
> +            Menu menuDB = _menuRepository.GetMenu(menuDate);
Меню на выбранную дату может не быть, в таком случае нужно вернуть пустое меню без блюд, чтобы на странице заказа не было возможности выбрать блюда для заказа

2019-06-03 21:23 UTC, Qmannn commented on FoodService/Startup.cs
> +            services.AddScoped<IRepository<Dish>, GenericRepository<Dish>>();
Поскольку IRepository<Dish> не используется, а используется IDishRepository можно не добавлять в сервисы  IRepository<Dish>

2019-06-03 21:23 UTC, Qmannn commented on Food.EntityFramework/Repository/DishRepository.cs
> +
тут два лишних пробела

2019-06-10 05:13 UTC, ondrosru commented on FoodService/Domain/Services/Finders/DailyMenuFinder.cs
> +            Menu menuDB = _menuRepository.GetMenu(menuDate);
Сделал

2019-06-10 05:13 UTC, ondrosru commented on FoodService/Startup.cs
> +            services.AddScoped<IRepository<Dish>, GenericRepository<Dish>>();
Удалил

2019-06-10 05:13 UTC, ondrosru commented on Food.EntityFramework/Repository/DishRepository.cs
> +
Удалил один лишний пробел

2019-06-10 15:39 UTC, merged