Добавление контекста и первой сущности БД
Qmannn/food-service pull request #12
Opened 2018-10-13 17:31 UTC by Frikikiki

2018-10-13 17:55 UTC, Qmannn commented on Food.EntityFramework/Entity/IEntity.cs
> +    interface IEntity
хорошим тоном считаю добавление модификатора доступа везде, даже по умолчанию устраивает (по умолчанию internal)
Думаю, что можно добавить internal
`internal interface IEntity`

2018-10-13 17:55 UTC, Qmannn commented on Food.EntityFramework/Entity/User.cs
> +    class User : IEntity
тоже надо бы добавить модификатор internal
Ну и заодно хорошо бы почитать про области видимости в C#

2018-10-13 17:55 UTC, Qmannn commented on Food.EntityFramework/Entity/User.cs
> +        public string Role { get; set; }
`public string Role { get; set; }` свойство можно удалить, поскольку роли будем разрешить иным путем, тут пока достаточно Id и имени пользователя

2018-10-13 17:55 UTC, Qmannn commented on Food.EntityFramework/FoodDbContext.cs
> +            Database.EnsureCreated();
`Database.EnsureCreated();` - довольно опасная штука. В случае, если будет допущена ошибка в конфигурации при деплое приложения на продакшн сред можно получить ситуацию, кода бд создастся заново и мы не сразу узнаем о том, что на самом деле приложение не использует нужную бд, а само создало новую. 
Лучше убрать вызов этого метода.

2018-10-13 17:55 UTC, Qmannn commented on Food.EntityFramework/Entity/User.cs
> +namespace Food.EntityFramework.Entity
Папку надо бы переназвать в Entities, поскольку в ней будут лежать все сущности бд

2018-10-13 17:56 UTC, Qmannn requested changes

2018-10-13 17:56 UTC, Qmannn commented on Food.EntityFramework/Entity/User.cs
> +        public string Role { get; set; }
public string Role { get; set; } свойство можно удалить, поскольку роли будем разрешить иным путем, тут пока достаточно Id и имени пользователя

2018-10-13 18:21 UTC, Frikikiki commented on Food.EntityFramework/Entity/IEntity.cs
> +    interface IEntity
поправил

2018-10-13 18:21 UTC, Frikikiki commented on Food.EntityFramework/Entity/User.cs
> +    class User : IEntity
поправил

2018-10-13 18:21 UTC, Frikikiki commented on Food.EntityFramework/Entity/User.cs
> +        public string Role { get; set; }
удалил

2018-10-13 18:21 UTC, Frikikiki commented on Food.EntityFramework/FoodDbContext.cs
> +            Database.EnsureCreated();
убрал

2018-10-13 18:22 UTC, Frikikiki commented on Food.EntityFramework/Entity/User.cs
> +namespace Food.EntityFramework.Entity
переименовал

2018-10-13 18:22 UTC, Frikikiki commented on Food.EntityFramework/Entity/User.cs
> +        public string Role { get; set; }
удалил

2018-10-13 21:26 UTC, Qmannn approved these changes

2018-10-13 21:26 UTC, Qmannn commented on Food.EntityFramework/FoodDbContext.cs
> +    class FoodDbContext : DbContext
`internal`

2018-10-14 04:29 UTC, AnastasiaKatelinskaya approved these changes

2018-10-14 09:09 UTC, Frikikiki commented on Food.EntityFramework/FoodDbContext.cs
> +    class FoodDbContext : DbContext
поправил

2018-10-14 11:14 UTC, merged