Добавление примера юнит теста
Qmannn/food-service pull request #14
Opened 2018-10-13 18:47 UTC by ondrosru

2018-10-13 21:24 UTC, Qmannn requested changes

2018-10-13 21:24 UTC, Qmannn commented on FoodService.Core.Tests/PrimeService_IsPrimeShould.cs
> +            Assert.False(result);
Все упоминания PrimeService(); можно удалить.
Для примера достаточно `Assert.False(false);`

2018-10-13 21:24 UTC, Qmannn commented on FoodService.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "FoodService.Core.Tests", "FoodService.Core.Tests\FoodService.Core.Tests.csproj", "{643BE3F7-00AC-46F4-A6D9-A382525CE257}"
Давай переименуем проект в `Food.Core.Tests` и переместим его в папку Tests, которую нужно добавить в солюшене.
Будет выглядеть как-то так
![image](https://user-images.githubusercontent.com/10262301/46910096-575adb80-cf47-11e8-9713-251d74490284.png)

2018-10-13 21:24 UTC, Qmannn commented on FoodService/PrimeService.cs
> +namespace Prime.Services
Этот файл нужно удалить

2018-10-14 12:55 UTC, Qmannn requested changes
Проект с тестами должен называться Food.Core.Tests
Надо его переименовать

2018-10-14 12:55 UTC, Qmannn commented on FoodService.Core.Tests/PrimeTests.cs
> +namespace Prime.UnitTests.Services
Пространство имен не соответствует расположению файла.
Должно быть Food.Core.Tests

2018-10-15 17:51 UTC, CaptainGlobers approved these changes

2018-10-15 21:18 UTC, Qmannn approved these changes

2018-10-16 09:54 UTC, closed without merging