Add food.core
Qmannn/food-service pull request #21
Opened 2018-10-14 17:29 UTC by kvladiimiir

2018-10-15 06:08 UTC, CaptainGlobers commented on Food/Food.cs
> +﻿using System;
Этот файл можно удалить

2018-10-15 06:53 UTC, Qmannn requested changes

2018-10-15 06:53 UTC, Qmannn commented on Food/Food.csproj
> +    <OutputType>Exe</OutputType>
Тип проекта должен быть "Библиотека классов" (Class Libraly)

2018-10-15 17:06 UTC, Qmannn requested changes
Название проекта нужно поменять на "Food.Core" и вытащить из папки Food(папка не нужна)

2018-10-15 17:39 UTC, Qmannn requested changes

2018-10-15 17:39 UTC, Qmannn commented on FoodService.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Food", "Food\Food.csproj", "{F17BEBAD-A338-4385-AB42-B913EBF33E4A}"
Проект не должен находиться в папке Food. Нужно переместить проект в корень солюшена и удалить папку Food

2018-10-16 21:19 UTC, Qmannn approved these changes
Нужно сделать Squash and merge

2018-10-20 06:18 UTC, merged