Реализация паттерна "Репозиторий"
Qmannn/food-service pull request #23
Opened 2018-10-15 14:29 UTC by SherlockD

Removing unused usings
Add IRepository interface
Add Repository abstract class
Add UserRepository

2018-10-15 14:54 UTC, Qmannn requested changes

2018-10-15 14:54 UTC, Qmannn commented on Food.EntityFramework/FoodDbContext.cs
> -    internal class FoodDbContext : DbContext
Файл нужно вернуть, `FoodDbContext ` - общий на проект контекст, добавление таблицы - есть добавление нового DbSet в это класс. UserDbContext надо грохнуть. Использовать FoodDbContext

2018-10-15 14:54 UTC, Qmannn commented on Food.EntityFramework/IRepository.cs
> +    interface IRepository<T>:IDisposable where T:class
1) T -> TEntrity
2) Для сущностей у нас определен интерфейс IEntity, используй его вместо class `where T: IEntity`
3) Ставь пробелы после :  читаемость повысится
4) Хорошим тоном является явное указание области видимости класса/интерфейса. Тут надо тоже указать internal , хоть он и проставляется по умолчанию

2018-10-15 14:54 UTC, Qmannn commented on Food.EntityFramework/IRepository.cs
> +        IEnumerable<T> GetList();
IEnumerable<T> GetList(); - так делать не надо, этот метод вытянет все данные из базы и вернет.
Для того, чтобы венуть список в возможность поиска по нему путем формирования запроса а потом его выполнения уже в бд (без извлечения всех данных таблицы) нужно использовать IQueryable<T>
Вместо метода `IEnumerable<T> GetList();` можно добавить свойство IQueryable<T> All { get; }
Потом можно будет использовать его как интерфейс для создания запросов.

2018-10-15 14:54 UTC, Qmannn commented on Food.EntityFramework/IRepository.cs
> +        void Create(T item);
Create и Update лучше объединить в метод Save(T item); А уже в репе разрулить создание/обновление по идентификатору

2018-10-15 14:54 UTC, Qmannn commented on Food.EntityFramework/Repository.cs
> +    abstract class Repository<C,T>:IRepository<T>,IDisposable where C: DbContext where T:class
Типы нужно именовать:
1) Всегда с буквы T
2) Чтобы было понятно что они означают 
Например: TDbContext, TEntity

2018-10-15 14:54 UTC, Qmannn commented on Food.EntityFramework/Repository.cs
> +    abstract class Repository<C,T>:IRepository<T>,IDisposable where C: DbContext where T:class
Не совсем ясна необходимость абстрактного класса
Достаточно было бы написать GenericRepository в параметрах которого фигурирует только тип сущности.
Так было бы достаточно одной реализации для большинства репозиториев, так же его можно было бы переопределять.

Давай так и сделаем.
Удалим abstract, Удалим в Generic параметрах тип DbContext (он один на приложение, так что не стоит его параметризировать), а в реализации для получения DbSet сущностей будем использовать метод
`private DbSet<TEntity> Table => _dbContext.Set<TEntity>();`

Таким образом реализации репозитории будут нужны только тогда, когда нужна какая-то особенная реализация, а для большинства классов будет подходить generic repository

2018-10-15 14:54 UTC, Qmannn commented on Food.EntityFramework/UserRepository.cs
> +    class UserRepository : Repository<UserDbContext, User>
Вместо UserRepository Давай сделаем GenericRepository<T> where T: IEntity

2018-10-15 14:54 UTC, Qmannn commented on Food.EntityFramework/UserRepository.cs
> +        private UserDbContext _userDbContext;
_userDbContext нужно инжектировать через конструктор, т.е. конструктор должен принимать в параметрах 
FoodDbContext (нужно для того, чтобы в дальнейшем можно было контролировать время жизни контекста средствами IoC - инверсии управления) Если интересно - расскажу подробнее при встрече

2018-10-15 14:54 UTC, Qmannn commented on Food.EntityFramework/UserRepository.cs
> +            System.GC.SuppressFinalize(this);
Во так вообще нужно делать только в крайнем случае :)

2018-10-15 14:54 UTC, Qmannn commented on Food.EntityFramework/UserDbContext.cs
> +    internal class UserDbContext : DbContext
Надо бы удалить этот контекст и вернуть FoodDbContext

2018-10-15 15:01 UTC, SherlockD commented on Food.EntityFramework/UserRepository.cs
> +            System.GC.SuppressFinalize(this);
Совсем удалить IDisposible?

2018-10-15 15:08 UTC, SherlockD commented on Food.EntityFramework/IRepository.cs
> +    interface IRepository<T>:IDisposable where T:class
Исправил

2018-10-15 15:09 UTC, SherlockD commented on Food.EntityFramework/Repository.cs
> +    abstract class Repository<C,T>:IRepository<T>,IDisposable where C: DbContext where T:class
Сделал

2018-10-15 15:14 UTC, SherlockD commented on Food.EntityFramework/UserRepository.cs
> +    class UserRepository : Repository<UserDbContext, User>
Сделал

2018-10-15 15:22 UTC, SherlockD commented on Food.EntityFramework/Repository.cs
> +    abstract class Repository<C,T>:IRepository<T>,IDisposable where C: DbContext where T:class
У нас будет получается только один DbContext для всех сущностей? Он называется FoodDbContext?

2018-10-15 17:48 UTC, SherlockD commented on Food.EntityFramework/Repository.cs
> +    abstract class Repository<C,T>:IRepository<T>,IDisposable where C: DbContext where T:class
Кстати насчет класса GenericRepository, если в будущем мы возможно будем его переопределять, будет ли уместно делать виртуальные методы или нет?

2018-10-15 18:39 UTC, Qmannn commented on Food.EntityFramework/Repository.cs
> +    abstract class Repository<C,T>:IRepository<T>,IDisposable where C: DbContext where T:class
1) Да, будет только один контекст и это FoodDbContext
2) Не, особого смысла нет, поскольку мы не будем менять поведение базовых методов, только расширять функицональность (добавлять новые методы) Например у нас есть метод получения сущности по ID а нам, внезапно, понадобится получать по Name - мы добавим наследника от репозитория (как ты сделал с UserRepository) и добавим туда только один метод, остальная же функциональность унаследуется от базового репозитория

2018-10-15 18:41 UTC, Qmannn commented on Food.EntityFramework/UserRepository.cs
> +            System.GC.SuppressFinalize(this);
Ну я имел в виду не делать так `System.GC.SuppressFinalize(this);`
но вообще - IDisposible нужен  в том случае, если тебе нужно дестроить какие-то экземпляры, которые ты сам создал. Поскольку теперь DbContext будет инжектироваться в конструктор - ты его не будешь сам создавать. **Не ты создал - не тебе и дестроить:)** Один из принципов, так сказать

2018-10-15 19:48 UTC, SherlockD commented on Food.EntityFramework/Repository.cs
> +    abstract class Repository<C,T>:IRepository<T>,IDisposable where C: DbContext where T:class
private DbSet<TEntity> Table => _dbContext.Set<TEntity>(); а метод это потому что, как я прочитал в книге свойства тоже как таковые методы. Кстати в книге автор выступил противником свойств, аргументируя это тем, что сильно ухудшается читаемость кода и еще что-то, не помню:)

2018-10-15 19:58 UTC, SherlockD commented on Food.EntityFramework/IRepository.cs
> +        void Create(T item);
А как же метод Save() который _foodDbContext.SaveChanges(); Он нужен?

2018-10-15 19:59 UTC, SherlockD commented on Food.EntityFramework/IRepository.cs
> +        IEnumerable<T> GetList();
Сделал

2018-10-15 19:59 UTC, SherlockD commented on Food.EntityFramework/FoodDbContext.cs
> -    internal class FoodDbContext : DbContext
Сделал

2018-10-15 19:59 UTC, SherlockD commented on Food.EntityFramework/UserRepository.cs
> +        private UserDbContext _userDbContext;
Готово

2018-10-15 19:59 UTC, SherlockD commented on Food.EntityFramework/UserRepository.cs
> +            System.GC.SuppressFinalize(this);
Сделал

2018-10-15 19:59 UTC, SherlockD commented on Food.EntityFramework/UserDbContext.cs
> +    internal class UserDbContext : DbContext
Готово

2018-10-15 20:05 UTC, SherlockD commented on Food.EntityFramework/Repository.cs
> +    abstract class Repository<C,T>:IRepository<T>,IDisposable where C: DbContext where T:class
Сделал

2018-10-15 20:06 UTC, SherlockD commented on Food.EntityFramework/IRepository.cs
> +        void Create(T item);
Я сделал метод Add, который будет объединением Create и Update

2018-10-15 21:15 UTC, Qmannn requested changes

2018-10-15 21:15 UTC, Qmannn commented on Food.EntityFramework/GenericRepository.cs
> +        public GenericRepository(FoodDbContext foodDbContext) {_foodDbContext = foodDbContext;}
Всегда тело метода/конструктора переносится на новые строки
`public GenericRepository(FoodDbContext foodDbContext) `
`{`
    `    _foodDbContext = foodDbContext;`
`}`

2018-10-15 21:15 UTC, Qmannn commented on Food.EntityFramework/GenericRepository.cs
> +        public void Create(TEntity item) { Table.Add(item); }
Тот же комментарий - переносим тело метода

2018-10-15 21:15 UTC, Qmannn commented on Food.EntityFramework/GenericRepository.cs
> +        public void Update(TEntity item) { _foodDbContext.Entry(item).State = EntityState.Modified; }
переносим тело метода

2018-10-15 21:15 UTC, Qmannn commented on Food.EntityFramework/GenericRepository.cs
> +        public void Update(TEntity item) { _foodDbContext.Entry(item).State = EntityState.Modified; }
Так для всех методов в классе

2018-10-15 21:15 UTC, Qmannn commented on Food.EntityFramework/GenericRepository.cs
> +        public void Add(TEntity item)
Add -> Save(TEntity item)
В методе Save нужно сделать 
Если IEntity.Id == 0 то вставить сущность
Иначе - обновить

2018-10-15 21:15 UTC, Qmannn commented on Food.EntityFramework/GenericRepository.cs
> +        public void Add(TEntity item)
Метод Add не нужен

2018-10-15 21:15 UTC, Qmannn commented on Food.EntityFramework/GenericRepository.cs
> +        public void Add(TEntity item)
Должен остаться только метод Save который знает как обработать добавление и обновление

2018-10-15 21:15 UTC, Qmannn commented on Food.EntityFramework/GenericRepository.cs
> +        private FoodDbContext _foodDbContext;
свойства, которые задаются в конструкторе и не изменяются во время жизни класса - нужно помечать модификатором readonly
`private readonly FoodDbContext _foodDbContext`

2018-10-15 21:15 UTC, Qmannn commented on Food.EntityFramework/GenericRepository.cs
> +        public void Add(TEntity item)
предлагаю такую реализацию 

        public TEntity Save( TEntity item )
        {
            TEntity savedEntity = item.Id == 0 
                ? Table.Add( item ).Entity 
                : Table.Update( item ).Entity;

            _foodDbContext.SaveChanges();

            return savedEntity;
        }

Возвращать сохраненное значение удобно, поскольку будет необходимо получить идентификатор сущности после сохранения

2018-10-15 21:15 UTC, Qmannn commented on Food.EntityFramework/GenericRepository.cs
> +            if (entity != null) Table?.Remove(entity);
_foodDbContext.SaveChanges();

2018-10-15 21:15 UTC, Qmannn commented on Food.EntityFramework/GenericRepository.cs
> +            if (entity != null) Table?.Remove(entity);
if всегда должен оборачиваться в фигурные скобки

    if (..)
    {
       ...
    }

2018-10-15 21:15 UTC, Qmannn commented on Food.EntityFramework/GenericRepository.cs
> +            if (entity != null) Table?.Remove(entity);
_foodDbContext.SaveChanges();

2018-10-15 21:15 UTC, Qmannn commented on Food.EntityFramework/IRepository.cs
> +    {
Тут еще нужно добавить свойство All

2018-10-15 21:15 UTC, Qmannn commented on Food.EntityFramework/IRepository.cs
> +        void Add(TEntity item);
Add и Save объединим и будем возвращаеть сохраненный объект

2018-10-16 05:53 UTC, SherlockD commented on Food.EntityFramework/GenericRepository.cs
> +        public void Add(TEntity item)
Сделал

2018-10-16 05:54 UTC, SherlockD commented on Food.EntityFramework/GenericRepository.cs
> +        private FoodDbContext _foodDbContext;
Сделал

2018-10-16 05:55 UTC, SherlockD commented on Food.EntityFramework/GenericRepository.cs
> +            if (entity != null) Table?.Remove(entity);
Готово

2018-10-16 05:55 UTC, SherlockD commented on Food.EntityFramework/GenericRepository.cs
> +            if (entity != null) Table?.Remove(entity);
Сделал

2018-10-16 05:55 UTC, SherlockD commented on Food.EntityFramework/GenericRepository.cs
> +            if (entity != null) Table?.Remove(entity);
Сделал

2018-10-16 05:56 UTC, SherlockD commented on Food.EntityFramework/IRepository.cs
> +    {
Сделал

2018-10-16 05:57 UTC, SherlockD commented on Food.EntityFramework/GenericRepository.cs
> +        public void Create(TEntity item) { Table.Add(item); }
Готово

2018-10-16 05:57 UTC, SherlockD commented on Food.EntityFramework/GenericRepository.cs
> +        public GenericRepository(FoodDbContext foodDbContext) {_foodDbContext = foodDbContext;}
Сделал

2018-10-16 05:58 UTC, SherlockD commented on Food.EntityFramework/GenericRepository.cs
> +        public void Update(TEntity item) { _foodDbContext.Entry(item).State = EntityState.Modified; }
Сделал

2018-10-16 05:58 UTC, SherlockD commented on Food.EntityFramework/IRepository.cs
> +        void Add(TEntity item);
Готово

2018-10-16 07:23 UTC, Qmannn requested changes

2018-10-16 07:23 UTC, Qmannn commented on Food.EntityFramework/GenericRepository.cs
> +        public void Update(TEntity item)
Этот метод абсолютно идентичен методу Save, только он работает более неявно

Сейчас от того, что в репозитории есть метод `Save()`  - без апраметров, который вызывает SaveChanges в DbContext - фактически этот репозиторий является реализацией паттрена UnitOfWork, это тоже отдельная история для разговора)
В целом мотод `public void Update(TEntity item)` не очень нужен, поскольку дублирует метод `Save(TEntity item)`
По этому же принциу не нужен метод `Create(TEntity item)` и 
Так же не нужен метод `Save()` 

Это все потому, что метод `TEntity Save(TEntity item)` заменяет все вышеперечисленные методы

2018-10-16 07:23 UTC, Qmannn commented on Food.EntityFramework/GenericRepository.cs
> +                Table?.Remove(entity);
? - оператор позволяющий избежать NullPointerReferenceException при обращении к переменной, в которой лежит null вместо экземпляра класса. 

? лишний, поскольку Table в этом месте  у тебя точно не null хотя бы потому, что на 55 строке ты к ней обращаешься без проверки.
На самом деле эта проверка не нужна, Table всегда должен быть не null/
Это исключение критическое , его отлавливать нужно на уровне всего приложения, а затем оповещать разработчика (это так, на будущее) :)

2018-10-16 07:23 UTC, Qmannn commented on Food.EntityFramework/GenericRepository.cs
> +        public void Save()
Метод удалим

2018-10-16 07:23 UTC, Qmannn commented on Food.EntityFramework/IRepository.cs
> +        void Save();
В интерфейсе как раз таки нет ненужных метоов кроме `void Save();.` его надо подгрохнуть

2018-10-16 07:47 UTC, SherlockD commented on Food.EntityFramework/GenericRepository.cs
> +                Table?.Remove(entity);
Да, я сознательно добавил этот символ, я просто подумал что нужно сделать проверку дабы не вызвать исключение. Но как я сейчас понял бороться с исключениями не есть правильно в данном случае)

2018-10-16 07:49 UTC, SherlockD commented on Food.EntityFramework/IRepository.cs
> +        void Save();
Сделал

2018-10-16 07:49 UTC, SherlockD commented on Food.EntityFramework/GenericRepository.cs
> +        public void Save()
Сделал

2018-10-16 07:49 UTC, SherlockD commented on Food.EntityFramework/GenericRepository.cs
> +                Table?.Remove(entity);
Сделал

2018-10-16 07:51 UTC, SherlockD commented on Food.EntityFramework/GenericRepository.cs
> +        public void Update(TEntity item)
Сделал

2018-10-16 07:56 UTC, Qmannn requested changes

2018-10-16 07:56 UTC, Qmannn commented on Food.EntityFramework/GenericRepository.cs
> +        public IQueryable All { get; }
`IQueryable<TEntity>`

2018-10-16 07:56 UTC, Qmannn commented on Food.EntityFramework/IRepository.cs
> +        IQueryable All { get; }
`IQueryable<TEntity>`

2018-10-16 08:05 UTC, SherlockD commented on Food.EntityFramework/GenericRepository.cs
> +        public IQueryable All { get; }
Исправил

2018-10-16 08:06 UTC, SherlockD commented on Food.EntityFramework/IRepository.cs
> +        IQueryable All { get; }
Исправил

2018-10-16 08:09 UTC, Qmannn approved these changes

2018-10-16 08:13 UTC, merged