Добавляю Db сущности в Food.EtityFramework
Qmannn/food-service pull request #29
Opened 2018-10-16 18:51 UTC by AnastasiaBastrakova

2018-10-16 21:28 UTC, Qmannn commented on Food.EntityFramework/Entities/Configurations/ContainerEntityTypeConfiguration.cs
> +            builder.Property(c => c.Name);
builder.Property(c => c.Name) - этот метод сам по себе ничего не делает. Таким образом ты не регистрируешь поле объекта.
Метод на самом деле возвращает специальный объект (PropertyBuilder) который так же имеет свои методы, с помощью которых можно модифицировать конфигурацию этого поля. 
Почитай про эту штуку.

2018-10-19 15:24 UTC, Qmannn requested changes

2018-10-19 15:24 UTC, Qmannn commented on Food.EntityFramework/Configurations/DishEntityTypeConfiguration.cs
> +            builder.Property(dish => dish.Price);
`builder.Property(dish => dish.Price);` такого рода записи не нужны, они фактически ничего не делают )

2018-10-19 15:24 UTC, Qmannn commented on Food.EntityFramework/Configurations/DishEntityTypeConfiguration.cs
> +            builder.Property(dish => dish.Name).IsRequired().HasMaxLength(40);
Давай длину увеличим до 500 символов

2018-10-19 15:24 UTC, Qmannn commented on Food.EntityFramework/Configurations/DishEntityTypeConfiguration.cs
> +            builder.ToTable("Dishes").HasKey(dish => dish.Id);
**Название таблиц**
1. Название такое же как сущность - Dish
2. Надо так сделать в каждой сущности

2018-10-19 15:24 UTC, Qmannn commented on Food.EntityFramework/Configurations/DishEntityTypeConfiguration.cs
> +            builder.Property(dish => dish.Description).IsRequired().HasMaxLength(400);
Тут нужно оставить длиту максимальной - HasMaxLength(400); можно удалить

2018-10-19 15:24 UTC, Qmannn commented on Food.EntityFramework/Entities/Configurations/UserEntityTypeConfiguration.cs
> +            builder.HasKey(c => c.Id);
Добавить ToTable

2018-10-19 15:24 UTC, Qmannn commented on Food.EntityFramework/Entities/Configurations/UserEntityTypeConfiguration.cs
> +            builder.Property(c => c.Role);
builder.Property надо удалить там где не используется

2018-10-19 15:24 UTC, Qmannn commented on Food.EntityFramework/Entities/Container.cs
> +        public int Price { get; set; }
Все денежное всегда используется с типом decimal. Не int, надо поменять

2018-10-19 15:24 UTC, Qmannn commented on Food.EntityFramework/Entities/Dish.cs
> +        public string Category { get; set; }
Категория должна быть перечислением.
Добавь перечисление (enum) с типами: салат, первое, второе, гарнир и сделай тут
public DishCategory Category { get; set; }

2018-10-19 15:24 UTC, Qmannn commented on Food.EntityFramework/Entities/Menu.cs
> +        public DateTime EndDate { get; set; }
Чтобы связать меню и список блюд нужно
0) Добавить связующую сущность `MenuDish`. Там будут поля MenuId DishId
И виртуальные свойства
`public virtual Menu Menu { get;set; }`
`public virtual Dish Dish { get;set; }`

1) В Menu  добавить виртуальное свойсво - коллекцию связей блюдо - меню
`public virtual ICollection<MenuDish> MenuDishes { get;set; }`
2) В классе Dish добавить виртуальное свойство - коллекцию меню 
`public virtual ICollection<MenuDish> MenuDishes { get;set; }`
3) В конфигурации меню (Menu) нужно описать связь меню и связующей таблицы

            builder.HasMany( menu => menu.MenuDishes )
                .WithOne( menuDish => menuDish.Menu  )
                .HasForeignKey( menuDish => menu.MenuId );

И такого рода штуки во всех конфигурациях нужно описать.
MenuDishes будет иметь отношение
HasOne(Menu).WithMany(MenuDishes) и т.д.

2018-10-19 15:24 UTC, Qmannn commented on Food.EntityFramework/FoodDbContext.cs
> +            modelBuilder.ApplyConfiguration(new ContainerConfiguration());
Такого рода штуковин можно избежать если доставать все конфигураторы из Assembly.
Пока объяснять как это работает нвверно не особо нужно. ПРосто замени эти строки (все 5)
на код 

            base.OnModelCreating( modelBuilder );

            var typesToRegister = Assembly.GetExecutingAssembly()
                .GetTypes()
                .Where( t => t.GetInterfaces().Any( gi => gi.IsGenericType && gi.GetGenericTypeDefinition() == typeof( IEntityTypeConfiguration<> ) ) )
                .ToList();


            foreach ( var type in typesToRegister )
            {
                dynamic configurationInstance = Activator.CreateInstance( type );
                modelBuilder.ApplyConfiguration( configurationInstance );
            }

2018-10-19 15:24 UTC, Qmannn commented on Food.EntityFramework/GenericRepository.cs
> +
Изменений тут не было, надо бы заревертить

2018-10-19 15:24 UTC, Qmannn commented on Food.EntityFramework/FoodDbContext.cs
> +        public DbSet<Container> Containers { get; set; }
Тут перечислять их не обязательно.
Давай уберем)

2018-10-19 15:24 UTC, Qmannn commented on Food.EntityFramework/Entities/Order.cs
> +    internal sealed class Order : IEntity
В каждой сущности помимо ссылкок на другие сущности в виде идентификаторов `UserId ` например, нужно писать виртуальные свойства - сами сущности.
 т.е если добавляешь ссылку на User (свойство UserId) то надо добавить и сущность User

`public virtual User User {get;set;}`

Это надо для того, чтобы в `IEntityTypeConfiguration` прописывать связи

Все эти HasOne WithOne / HasOne WithMany/ HasMany WithOne

Тут так же есть ссылка на меню - надо добавить Menu свойство и описать связь.
Описываем связи для того, чтобы у таблиц был определен внешний ключ.
Он в свою очередь необходи для поддержания бд в состоянии связанности

2018-10-19 15:24 UTC, Qmannn commented on Food.EntityFramework/Configurations/ContainerEntityTypeConfiguration.cs
> +            builder.ToTable("Containers").HasKey(container => container.Id);
В каждой сущности нужно прописать связи. Ниже написал как это сделать.

2018-10-22 12:40 UTC, AnastasiaBastrakova commented on Food.EntityFramework/Configurations/DishEntityTypeConfiguration.cs
> +            builder.ToTable("Dishes").HasKey(dish => dish.Id);
Поправила

2018-10-22 12:43 UTC, AnastasiaBastrakova commented on Food.EntityFramework/GenericRepository.cs
> +
Заревертила

2018-10-22 12:45 UTC, AnastasiaBastrakova commented on Food.EntityFramework/Configurations/DishEntityTypeConfiguration.cs
> +            builder.Property(dish => dish.Name).IsRequired().HasMaxLength(40);
Сделала

2018-10-22 12:48 UTC, AnastasiaBastrakova commented on Food.EntityFramework/Entities/Configurations/UserEntityTypeConfiguration.cs
> +            builder.HasKey(c => c.Id);
Добавила

2018-10-22 12:52 UTC, AnastasiaBastrakova commented on Food.EntityFramework/Configurations/DishEntityTypeConfiguration.cs
> +            builder.Property(dish => dish.Description).IsRequired().HasMaxLength(400);
Исправила

2018-10-22 12:54 UTC, AnastasiaBastrakova commented on Food.EntityFramework/Entities/Container.cs
> +        public int Price { get; set; }
Поменяла

2018-10-22 12:59 UTC, AnastasiaBastrakova commented on Food.EntityFramework/FoodDbContext.cs
> +        public DbSet<Container> Containers { get; set; }
Убрала

2018-10-22 13:07 UTC, AnastasiaBastrakova commented on Food.EntityFramework/Configurations/DishEntityTypeConfiguration.cs
> +            builder.Property(dish => dish.Price);
Поправила

2018-10-22 13:08 UTC, AnastasiaBastrakova commented on Food.EntityFramework/Entities/Configurations/UserEntityTypeConfiguration.cs
> +            builder.Property(c => c.Role);
Поправила

2018-10-22 13:33 UTC, AnastasiaBastrakova commented on Food.EntityFramework/Entities/Dish.cs
> +        public string Category { get; set; }
Исправила

2018-10-22 14:25 UTC, AnastasiaKatelinskaya commented on Food.EntityFramework/FoodDbContext.cs
> +            modelBuilder.ApplyConfiguration(new ContainerConfiguration());
Заменила

2018-10-22 20:55 UTC, AnastasiaBastrakova commented on Food.EntityFramework/Entities/Menu.cs
> +        public DateTime EndDate { get; set; }
Сделала

2018-10-22 21:27 UTC, Qmannn requested changes

2018-10-22 21:27 UTC, Qmannn commented on Food.EntityFramework/Entities/Configurations/ContainerEntityTypeConfiguration.cs
> +            builder.HasMany(dish => dish.Dishes)
Первый HasMany описывает элемент в типе, для которого реализуется конфигурация.
т.е. Container

```
builder.HasMany(container => container .Dishes)
    .WithOne(dish => dish.Container)
     ...
```

2018-10-22 21:27 UTC, Qmannn commented on Food.EntityFramework/Entities/Configurations/DishEntityTypeConfiguration.cs
> +                .HasForeignKey(orderDish => orderDish.OrderDishId);
ForeignKey - это внешний ключ для таблицы OrderDish к таблице Dish
Внешним ключом является поле-ссылка на зависимую таблицу.
Внешний ключ всегда связывается с первичным ключом таблицы.
То есть Блюда связаны с БлюдоВЗаказе полями Dish.Id -> OrderDish.DishId
`.HasForeignKey(orderDish => orderDish.DishId);`

2018-10-22 21:27 UTC, Qmannn commented on Food.EntityFramework/Entities/Configurations/DishEntityTypeConfiguration.cs
> +                .HasForeignKey(menuDish => menuDish.MenuDishId);
`.HasForeignKey(menuDish => menuDish.DishId);`

2018-10-22 21:27 UTC, Qmannn commented on Food.EntityFramework/Entities/Configurations/MenuEntityTypeConfiguration.cs
> +            builder.Property(menu => menu.CurrentDate);
builder.Property(menu => menu.CurrentDate); - такие строки не нужны. Они ничего не делают. Если после вызова Property ничего не вызывается в роде `Property(...).IsRequired();` то такие вызовы нужно удалить

2018-10-22 21:27 UTC, Qmannn commented on Food.EntityFramework/Entities/Configurations/MenuEntityTypeConfiguration.cs
> +                .WithOne(menuDishes => menuDishes.Menu)
menuDish (ед. число)

2018-10-22 21:27 UTC, Qmannn commented on Food.EntityFramework/Entities/Configurations/MenuEntityTypeConfiguration.cs
> +                .WithOne(menu => menu.Menu)
.HasForeignKey(...);

2018-10-22 21:27 UTC, Qmannn commented on Food.EntityFramework/Entities/Configurations/OrderEntityTypeConfiguration.cs
> +            builder.Property(order => order.DeliveryDate);
builder.Property(order => order.DeliveryDate);
builder.Property(order => order.OrderDate);
Эти строки нужно удалить

2018-10-22 21:27 UTC, Qmannn commented on Food.EntityFramework/Entities/Configurations/OrderEntityTypeConfiguration.cs
> +            builder.HasOne(user => user.User)
Чет тут с именованиями пошло не так, надо бы поправить. Похоже сначала должны быть HasOne(order => order.User)

2018-10-22 21:27 UTC, Qmannn commented on Food.EntityFramework/Entities/Configurations/OrderEntityTypeConfiguration.cs
> +               .WithMany(order => order.Orders)
HasForeignKey

2018-10-22 21:27 UTC, Qmannn commented on Food.EntityFramework/Entities/Configurations/OrderEntityTypeConfiguration.cs
> +               .WithMany(order => order.Orders)
HasForeignKey

2018-10-22 21:27 UTC, Qmannn commented on Food.EntityFramework/Entities/Configurations/UserEntityTypeConfiguration.cs
> +            builder.HasMany(order => order.Orders)
тоже именования поехали, надо бы поправить. `builder.HasMany(user => user.Orders)`

2018-10-22 21:27 UTC, Qmannn commented on Food.EntityFramework/Entities/Configurations/UserEntityTypeConfiguration.cs
> +                .WithOne(user => user.User)
HasForeignKey

2018-10-22 21:27 UTC, Qmannn commented on Food.EntityFramework/Entities/Dish.cs
> +        public Dish()
Конструктор не обязателен

2018-10-22 21:27 UTC, Qmannn commented on Food.EntityFramework/Entities/Dish.cs
> +        public virtual List<MenuDish> MenuDishes { get; set; }
List -> ICollection тут и везде в других опианиях сущностей

2018-10-22 21:27 UTC, Qmannn commented on Food.EntityFramework/Entities/MenuDish.cs
> +    internal class MenuDish
Класс должен содержать ссылку на блюдо (DishId) и ссылку на меню MenuId, больше никаких свойств быть не должно.
С помощью этих свойств и будут образованы связи. 
Я так понимю тут нужно просто переименовать MenuDishId в DishId

2018-10-22 21:27 UTC, Qmannn commented on Food.EntityFramework/Entities/Order.cs
> +        public virtual Menu Menu { get; set; }
Виртуальный свойства нужно описать в самом низу класса.

2018-10-22 21:27 UTC, Qmannn commented on Food.EntityFramework/Entities/OrderDish.cs
> +        public int OrderDishId { get; set; }
OrderDishId => DishId

2018-10-23 05:45 UTC, AnastasiaBastrakova commented on Food.EntityFramework/Entities/MenuDish.cs
> +    internal class MenuDish
Исправила вторую партию ошибок

2018-10-23 08:33 UTC, CaptainGlobers approved these changes

2018-10-23 15:57 UTC, Qmannn requested changes

2018-10-23 15:57 UTC, Qmannn commented on Food.EntityFramework/Entities/Configurations/DishEntityTypeConfiguration.cs
> +            builder.Property(dish => dish.Category).IsRequired().HasMaxLength(500);
dish.Category это не строка, .HasMaxLength(500); - не нужен

2018-10-23 15:57 UTC, Qmannn commented on Food.EntityFramework/Entities/Configurations/DishEntityTypeConfiguration.cs
> +                .HasForeignKey(orderDish => orderDish.DishId);
builder.HasMany(dish => dish.OrderDishes)
                .WithOne(orderDish => orderDish.Dish)
                .HasForeignKey(orderDish => orderDish.DishId);

Это не нужно.
Блюдо в заказе не совсем аналогично блюду в меню.
Блюдо в заказе должно быть отдельной сущностью со всеми теми же полями, что есть у Блюда.
 Нужно для того, чтобы фиксировать свойства блюда на момент заказа.

Order имеет свойство Id
OrderDish имеет свойство OrderId, а так же повторяет все поля Dish

2018-10-24 05:19 UTC, AnastasiaBastrakova commented on Food.EntityFramework/Entities/Configurations/DishEntityTypeConfiguration.cs
> +                .HasForeignKey(orderDish => orderDish.DishId);
Поправила

2018-10-24 05:23 UTC, AnastasiaKatelinskaya commented on Food.EntityFramework/Entities/Configurations/DishEntityTypeConfiguration.cs
> +                .HasForeignKey(orderDish => orderDish.DishId);
Я правильно поняла, что с таблицей Dish таблица OrderDish не связана совсем?

2018-10-24 06:33 UTC, Qmannn requested changes

2018-10-24 06:33 UTC, Qmannn commented on Food.EntityFramework/Entities/Configurations/OrderEntityTypeConfiguration.cs
> +            builder.HasOne(order => order.OrderDishes)
Вместо HasOne наверно должно быть HasMany
В заказе может быть несколько блюд

2018-10-24 06:33 UTC, Qmannn commented on Food.EntityFramework/Entities/OrderDish.cs
> +    internal class OrderDish
Реализуй IEntity, чтобы у OrderDish появилось свойство Id
Затем в OrderDishConfiguration надо бы поправить ошибку сборки - там несуществующее свойство используется.
Ключ будет состоять только из Id - он уникален будет.

2018-10-24 12:16 UTC, AnastasiaBastrakova commented on Food.EntityFramework/Entities/Configurations/OrderEntityTypeConfiguration.cs
> +            builder.HasOne(order => order.OrderDishes)
Сделала

2018-10-24 12:16 UTC, AnastasiaBastrakova commented on Food.EntityFramework/Entities/OrderDish.cs
> +    internal class OrderDish
Сделала

2018-10-24 14:10 UTC, Qmannn approved these changes

2018-10-24 20:14 UTC, merged