Реализация возможности добавления параметров приложения
Qmannn/food-service pull request #30
Opened 2018-10-17 14:07 UTC by SherlockD

2018-10-19 14:14 UTC, Qmannn requested changes

2018-10-19 14:14 UTC, Qmannn commented on FoodService/Config/ApplicationConfig.cs
> +        public static IConfiguration GetServiceConfiguration()
Давай этот метод сделаем приватным.
Класс не будем делать статичным, потому что такие классы не поддаются инжектированию, а следовательно везде где они используются - тестирование будет затруднено.

Так же давай свойство DbContextConfiguration перенесем в этот класс и наружу будет торачать только оно. Логику именования секций в конфигурации спрячем в этом классе

2018-10-19 14:14 UTC, Qmannn commented on FoodService/Startup.cs
> +        public DbContextConfiguration dbContextConfiguration = ApplicationConfig.GetServiceConfiguration().GetSection("DbContextConfiguration").Get<DbContextConfiguration>();
Эту строку перенесем в ApplicationConfig

2018-10-19 18:00 UTC, Qmannn commented on FoodService/Config/ApplicationConfig.cs
> +        public static IConfiguration GetServiceConfiguration()
Должен получиться класс ApplicationConfig в конструкторе которого вызывается метод  
GetServiceConfiguration, результат выполнения которого сохраняется в приватном поле класса.
private readonly IServiceConfiguration _serviceConfiguration;

Так же в классе должно быть пока одно публичное свойство
`public DbContextConfiguration  DbContextConfiguration => _serviceConfiguration.GetSection("DbContextConfiguration").Get<DbContextConfiguration>();`

таким образом один класс ApplicationConfig предоставит доступ ко всем доступным в json секциям. Сюда же мы можем положить дополнительные конфигурации, если они понадобятся.

2018-10-21 15:14 UTC, SherlockD commented on FoodService/Config/ApplicationConfig.cs
> +        public static IConfiguration GetServiceConfiguration()
Сделал

2018-10-21 15:14 UTC, SherlockD commented on FoodService/Startup.cs
> +        public DbContextConfiguration dbContextConfiguration = ApplicationConfig.GetServiceConfiguration().GetSection("DbContextConfiguration").Get<DbContextConfiguration>();
Сделал

2018-10-21 15:45 UTC, Qmannn approved these changes

2018-10-21 15:46 UTC, merged