Добавление страницы списка меню на каждый день
Qmannn/food-service pull request #37
Opened 2018-10-29 16:40 UTC by SherlockD

2018-10-30 21:03 UTC, Qmannn requested changes
Необходимо сделать rebase c dev веткой
Там есть некоторые изменения

2018-10-30 21:03 UTC, Qmannn commented on FoodAdmin/ClientApp/src/HttpServices/MenuDataHttpService.ts
> +export class MenuDataHttpService {
MenusHttpService
Название сервиса должно совпадать с префиксом контроллера
MenusApiController -> MenusHttpService
UserApiController -> UserHttpService и так далее

2018-10-30 21:03 UTC, Qmannn commented on FoodAdmin/ClientApp/src/components/pages/menu/menu.component.html
> +    <td>{{sample.menuId}}</td>
sample и samples надо бы переименовать в то, что там действительно лежит

2018-10-30 21:03 UTC, Qmannn commented on FoodAdmin/ClientApp/src/components/pages/menu/menu.component.ts
> +  selector: 'app-menu',
app-menu-list поскольку app-menu похоже на "Меню приложения".

2018-10-30 21:03 UTC, Qmannn commented on FoodAdmin/ClientApp/src/components/pages/menu/menu.component.ts
> +  public countAll = 0;
countAll этосвойство нужно?

2018-10-30 21:03 UTC, Qmannn commented on FoodAdmin/ClientApp/src/components/pages/menu/menu.component.ts
> +  public samples: MenuDto[];
samples - menus
Название должно соответствовать действительности

2018-10-30 21:03 UTC, Qmannn commented on FoodAdmin/ClientApp/src/HttpServices/MenuDataHttpService.ts
> +    public getSamples(): Observable<MenuDto[]> {
getSamples -> getMenus
Очень внимательно нужно следить за именованием

2018-10-31 14:30 UTC, SherlockD commented on FoodAdmin/ClientApp/src/HttpServices/MenuDataHttpService.ts
> +export class MenuDataHttpService {
Сделал

2018-10-31 14:33 UTC, SherlockD commented on FoodAdmin/ClientApp/src/HttpServices/MenuDataHttpService.ts
> +export class MenuDataHttpService {
Сделал

2018-10-31 14:34 UTC, SherlockD commented on FoodAdmin/ClientApp/src/components/pages/menu/menu.component.html
> +    <td>{{sample.menuId}}</td>
Сделал

2018-10-31 14:35 UTC, SherlockD commented on FoodAdmin/ClientApp/src/components/pages/menu/menu.component.ts
> +  selector: 'app-menu',
Сделал

2018-10-31 14:35 UTC, SherlockD commented on FoodAdmin/ClientApp/src/components/pages/menu/menu.component.ts
> +  public countAll = 0;
убрал

2018-10-31 14:35 UTC, SherlockD commented on FoodAdmin/ClientApp/src/components/pages/menu/menu.component.ts
> +  public samples: MenuDto[];
готово

2018-10-31 14:35 UTC, SherlockD commented on FoodAdmin/ClientApp/src/HttpServices/MenuDataHttpService.ts
> +    public getSamples(): Observable<MenuDto[]> {
Исправил, в будущем буду внимательнее

2018-10-31 14:37 UTC, SherlockD commented on FoodAdmin/ClientApp/src/components/pages/menu/menu.component.ts
> +  public countAll = 0;
удалил

2018-10-31 16:49 UTC, Qmannn requested changes

2018-10-31 16:49 UTC, Qmannn commented on FoodAdmin/ClientApp/src/components/pages/menu/menu.component.html
> +<<<<<<< HEAD
Осталась строка после rebase

2018-10-31 16:49 UTC, Qmannn commented on FoodAdmin/ClientApp/src/components/pages/menu/menu.component.html
> +=======
Что-то пошло не так

2018-10-31 16:49 UTC, Qmannn commented on FoodAdmin/Controllers/MenusApiController.cs
> +        public List<MenuDto> GetSamples()
GetMenus

2018-10-31 16:49 UTC, Qmannn commented on FoodAdmin/Controllers/SampleDataController.cs
> +    public class SampleDataController : Controller
SampleDataController я удалил, а после ребейза у тебя он остался. Надо бы грохнуть этот файл

2018-10-31 16:49 UTC, Qmannn commented on FoodAdmin/Dto/Menu/MenuDto.cs
> +        public bool MenuStatus { get; set; }
Статусы обычно описываются с помощью Enum-ов
Добавь enum MenuStatus со значениями Active и Closed. Пока этого достаточно
bool лишком не гибко

2018-11-01 07:53 UTC, SherlockD commented on FoodAdmin/Dto/Menu/MenuDto.cs
> +        public bool MenuStatus { get; set; }
Сделал

2018-11-01 07:53 UTC, SherlockD commented on FoodAdmin/Controllers/SampleDataController.cs
> +    public class SampleDataController : Controller
Удалил

2018-11-01 07:54 UTC, SherlockD commented on FoodAdmin/Controllers/MenusApiController.cs
> +        public List<MenuDto> GetSamples()
Извиняюсь, я вчера когда разбирался с ребейсом, по 4 раза изменял предыдущие пункты, видимо про это забыл

2018-11-01 07:55 UTC, SherlockD commented on FoodAdmin/ClientApp/src/components/pages/menu/menu.component.html
> +<<<<<<< HEAD
Здесь почему то мой коммит не вошел в push, странно, у меня этих строк нет в проекте, сейчас попробую снова закоммитить

2018-11-02 05:26 UTC, Qmannn approved these changes

2018-11-02 05:26 UTC, Qmannn commented on FoodAdmin/Controllers/MenusApiController.cs
> +                    MenuStatus = MenuStatus.Closed.ToString()
Так-то все бы норм, но было бы лучше, если значение Enum-а будет передаваться на фронтенд, а текст, который нужно показать в колонке "Статус" резолвился бы уже на фронтенде. Но пока можно оставить

2018-11-02 05:26 UTC, Qmannn commented on FoodAdmin/Dto/Menu/MenuStatus.cs
> +    {
Что-то с пробелами, надо бы отформатировать

2018-11-07 09:33 UTC, CaptainGlobers approved these changes
ребейз и можно сливать

2018-12-12 13:54 UTC, SherlockD commented on FoodAdmin/Dto/Menu/MenuStatus.cs
> +    {
Исправил

2018-12-12 14:11 UTC, SherlockD commented on FoodAdmin/Controllers/MenusApiController.cs
> +                    MenuStatus = MenuStatus.Closed.ToString()
Я не очень понимаю как в ts можно enum в string превратить, искал сейчас в интернете ничего не нашел

2018-12-13 16:41 UTC, SherlockD commented on FoodAdmin/Controllers/MenusApiController.cs
> +                    MenuStatus = MenuStatus.Closed.ToString()
Исправил

2018-12-20 08:22 UTC, merged