Add FoodList
Qmannn/food-service pull request #39
Opened 2018-10-31 13:13 UTC by kvladiimiir

2018-10-31 19:15 UTC, Qmannn requested changes

2018-10-31 19:15 UTC, Qmannn commented on FoodAdmin/ClientApp/src/components/pages/Food-List/FoodList.Component.ts
> +  public FoodList: FoodListDto[];
1) Думаю, лучше оперировать названием "Блюдо" - Dish
тогда свойство это будет называться dishes
2) в ts переменные принято именовать в lowerCamelCase
public varibleName: number;
private readonly _varibleName: number;

2018-10-31 19:15 UTC, Qmannn commented on FoodAdmin/ClientApp/src/dto/FoodListDto/FoodListDto.ts
> +export class FoodListDto {
1) Название не совсем верно. Эта Dto описывает один экземпляр Блюда, а название говорит о том, что это целый список
2) везде где Food нужно поправить на Dish
3) На бекенде так же нужно переименовать класс

2018-10-31 19:15 UTC, Qmannn commented on FoodAdmin/ClientApp/src/dto/FoodListDto/FoodListDto.ts
> +  public PriceFood: number;
Названия такого рода переменных нужно писать в одном стиле
Есть два пути, либо писать название сущности+свойство либо просто свойство

DishName или Name
DishPrice или Price
DishType или Type

2018-10-31 19:15 UTC, Qmannn commented on FoodAdmin/Controllers/FoodList/FoodListController.cs
> +        public List<FoodListDto> GetSamples()
GetDishes

2018-10-31 19:15 UTC, Qmannn commented on FoodAdmin/Controllers/FoodList/FoodListController.cs
> +        [HttpGet("foodlist")]
dishes - коротко и понятно

2018-10-31 19:15 UTC, Qmannn commented on FoodAdmin/Dto/FoodList/FoodListDto.cs
> +        public string TypeFood { get; set; }
1) FoodType
2) Фиксированные типы обычно описываются с помощью enum-ов
Нужно добавить enum c 4 значениями, и передавать его на фронтенд
На фронтенде нужно так же описать этот enum

2018-10-31 19:15 UTC, Qmannn commented on FoodAdmin/Controllers/FoodList/FoodListController.cs
> +    public class FoodListController : Controller
Давай назовем этот класс DishesApiController
И на фронтенде переименуем сервис

2018-10-31 19:15 UTC, Qmannn commented on FoodAdmin/ClientApp/src/app.module.ts
> +import { FoodListComponent } from './components/pages/Food-List/FoodList.Component';
Папку с названием страницы нужно так же называть в UpperCamelCase, дефисы использовать не нужно

2018-11-23 06:19 UTC, Qmannn requested changes

2018-11-23 06:19 UTC, Qmannn commented on FoodAdmin/Dto/DishList/DishList.cs
> +    public class DishDto
Название файл DishList.cs не соответствует названию класса DishDto, хорошо бы поправить

2018-11-23 06:19 UTC, Qmannn commented on FoodAdmin/Dto/DishList/DishList.cs
> +        public int DishPrice { get; set; }
Поскольку стоимость может быть с копейками, например, необходимо для стоимости использовть число с плавающей точкой. 
Для измерения денежных единиц используется тип decimal

Надо сделать: исправить int на decimal

2018-11-23 06:19 UTC, Qmannn commented on FoodAdmin/FoodAdmin.csproj
> +
Эти 4 строки нужно удалить.
Фактически это блок , добавляющий файлы ts которые будут компилироваться, однако мы не сипользуем компиляцию TS в VS, а собираем с помощью webpaсk.

Решение: удалить эти строки

2018-11-23 06:19 UTC, Qmannn commented on FoodAdmin/FoodAdmin.csproj
> +    <Compile Remove="ClientApp\src\dto\Новая папка\**" />
В этом файле все изменения надо бы откатить

2018-11-23 06:19 UTC, Qmannn commented on FoodAdmin/Dto/DishList/Enum/DishType.cs
> +﻿namespace FoodAdmin.Dto.DishList.Enum
В принципе, отдельную папку Enum создавать не обязательно, Перечисления это такие же элементы, как классы, можно их в одну папку скалдывать с тем классом, где они используются, например в FoodAdmin.Dto.DishList.

Нужно ли переделывать - на твое усмотрение.

2018-11-23 06:19 UTC, Qmannn commented on FoodAdmin/ClientApp/src/environments/environment.ts
> +  baseUrl: 'http://localhost:52182/'
Тут нужно вернуть порт 55222.
Чтобы работало нормлаьно - лучше настроить запуск из VS на этом же порту.
Делается вот тут http://joxi.ru/krD4KvMHEkXOVr

2018-11-23 06:19 UTC, Qmannn commented on FoodAdmin/ClientApp/src/dto/DishDto/Enum/DishType.js.map
> +{"version":3,"file":"DishType.js","sourceRoot":"","sources":["DishType.ts"],"names":[],"mappings":";;AAAA,IAAY,QAKX;AALD,WAAY,QAAQ;IAClB,yCAAK,CAAA;IACL,uCAAI,CAAA;IACJ,mDAAU,CAAA;IACV,6CAAO,CAAA;AAC
Файл нужно удалить
Это файл, который был сгенерировать при сборке, они не должны попадать в коммит.
Чтобы эти файлы не генерились требуются некоторые доработки, сделаю их в DEV сам.
Пока просто удали их из проекта

2018-11-23 06:19 UTC, Qmannn commented on FoodAdmin/ClientApp/src/dto/DishDto/Enum/DishType.js
> +"use strict";
Файл нужно удалить.
Та же история, что с DishType.js.map

2018-11-23 06:19 UTC, Qmannn commented on FoodAdmin/ClientApp/src/dto/DishDto/DishDto.js.map
> +{"version":3,"file":"DishDto.js","sourceRoot":"","sources":["DishDto.ts"],"names":[],"mappings":";;AAAA;IAAA;IAIA,CAAC;IAAD,cAAC;AAAD,CAAC,AAJD,IAIC;AAJY,0BAAO;AAKpB,IAAK,QAKJ;AALD,WAAK,QAAQ;IACX,yCA
Нужно удалить файл

2018-11-23 06:19 UTC, Qmannn commented on FoodAdmin/ClientApp/src/dto/DishDto/DishDto.js
> +"use strict";
Нужно удалить файл

2018-11-23 06:19 UTC, Qmannn commented on .vscode/launch.json
> +{
Файл тоже надо бы удалить

2018-11-23 20:59 UTC, kvladiimiir commented on FoodAdmin/Dto/FoodList/FoodListDto.cs
> +        public string TypeFood { get; set; }
сделано

2018-11-23 20:59 UTC, kvladiimiir commented on FoodAdmin/Controllers/FoodList/FoodListController.cs
> +    public class FoodListController : Controller
сделано

2018-11-23 20:59 UTC, kvladiimiir commented on FoodAdmin/Controllers/FoodList/FoodListController.cs
> +        [HttpGet("foodlist")]
сделано

2018-11-23 20:59 UTC, kvladiimiir commented on FoodAdmin/Controllers/FoodList/FoodListController.cs
> +        public List<FoodListDto> GetSamples()
сделано

2018-11-23 21:00 UTC, kvladiimiir commented on FoodAdmin/ClientApp/src/dto/FoodListDto/FoodListDto.ts
> +  public PriceFood: number;
сделал DishName DishPrice DishType

2018-11-23 21:00 UTC, kvladiimiir commented on FoodAdmin/ClientApp/src/dto/FoodListDto/FoodListDto.ts
> +export class FoodListDto {
сделано

2018-11-23 21:00 UTC, kvladiimiir commented on FoodAdmin/ClientApp/src/components/pages/Food-List/FoodList.Component.ts
> +  public FoodList: FoodListDto[];
сделано

2018-11-23 21:01 UTC, kvladiimiir commented on FoodAdmin/ClientApp/src/app.module.ts
> +import { FoodListComponent } from './components/pages/Food-List/FoodList.Component';
сделано

2018-11-23 21:31 UTC, kvladiimiir commented on FoodAdmin/ClientApp/src/environments/environment.ts
> +  baseUrl: 'http://localhost:52182/'
Немного не понял по скриншоту, где у нас находится данный файл, где можно настроить порт для запуска?

2018-11-23 21:34 UTC, kvladiimiir commented on FoodAdmin/Dto/DishList/DishList.cs
> +    public class DishDto
сделано

2018-11-23 21:34 UTC, kvladiimiir commented on FoodAdmin/Dto/DishList/DishList.cs
> +        public int DishPrice { get; set; }
сделано

2018-11-23 21:35 UTC, kvladiimiir commented on FoodAdmin/Dto/DishList/Enum/DishType.cs
> +﻿namespace FoodAdmin.Dto.DishList.Enum
Я не поменял, просто вроде тогда говорили на занятии, чтобы все было в отдельных папках и файлах) Ну и сделал как в примере.

2018-11-23 21:42 UTC, kvladiimiir commented on FoodAdmin/ClientApp/src/dto/DishDto/Enum/DishType.js.map
> +{"version":3,"file":"DishType.js","sourceRoot":"","sources":["DishType.ts"],"names":[],"mappings":";;AAAA,IAAY,QAKX;AALD,WAAY,QAAQ;IAClB,yCAAK,CAAA;IACL,uCAAI,CAAA;IACJ,mDAAU,CAAA;IACV,6CAAO,CAAA;AAC
Мне просто удалить эти файлы, или как-то по-другому, например добавить в gitignore

2018-11-23 21:58 UTC, Qmannn commented on FoodAdmin/ClientApp/src/dto/DishDto/Enum/DishType.js.map
> +{"version":3,"file":"DishType.js","sourceRoot":"","sources":["DishType.ts"],"names":[],"mappings":";;AAAA,IAAY,QAKX;AALD,WAAY,QAAQ;IAClB,yCAAK,CAAA;IACL,uCAAI,CAAA;IACJ,mDAAU,CAAA;IACV,6CAAO,CAAA;AAC
Пока достаточно просто удалить. Я чуть позже сделаю Доработкк, чтобы они не создавались.
Они создаются из-за неверной настройки проекта

2018-11-23 21:59 UTC, Qmannn commented on FoodAdmin/Dto/DishList/Enum/DishType.cs
> +﻿namespace FoodAdmin.Dto.DishList.Enum
Ок, хорошо, пусть пока так. Просто на папки разбивать хорошо, но нужно делать это вмеру, чтобы было не очень сложно)

2018-11-25 17:08 UTC, kvladiimiir commented on .vscode/launch.json
> +{
сделано

2018-11-25 17:08 UTC, kvladiimiir commented on FoodAdmin/ClientApp/src/dto/DishDto/DishDto.js
> +"use strict";
сделано

2018-11-25 17:08 UTC, kvladiimiir commented on FoodAdmin/ClientApp/src/dto/DishDto/DishDto.js.map
> +{"version":3,"file":"DishDto.js","sourceRoot":"","sources":["DishDto.ts"],"names":[],"mappings":";;AAAA;IAAA;IAIA,CAAC;IAAD,cAAC;AAAD,CAAC,AAJD,IAIC;AAJY,0BAAO;AAKpB,IAAK,QAKJ;AALD,WAAK,QAAQ;IACX,yCA
сделано

2018-11-25 17:08 UTC, kvladiimiir commented on FoodAdmin/ClientApp/src/dto/DishDto/Enum/DishType.js
> +"use strict";
сделано

2018-11-25 17:09 UTC, kvladiimiir commented on FoodAdmin/ClientApp/src/dto/DishDto/Enum/DishType.js.map
> +{"version":3,"file":"DishType.js","sourceRoot":"","sources":["DishType.ts"],"names":[],"mappings":";;AAAA,IAAY,QAKX;AALD,WAAY,QAAQ;IAClB,yCAAK,CAAA;IACL,uCAAI,CAAA;IACJ,mDAAU,CAAA;IACV,6CAAO,CAAA;AAC
сделано

2018-11-25 17:10 UTC, kvladiimiir commented on FoodAdmin/FoodAdmin.csproj
> +
сделано

2018-11-25 17:46 UTC, kvladiimiir commented on FoodAdmin/FoodAdmin.csproj
> +    <Compile Remove="ClientApp\src\dto\Новая папка\**" />
я откатил изменения, потом запустил, и у меня походу опять все так же, вот скинул скрины, посмотрите пожалуйста
![1](https://user-images.githubusercontent.com/32225962/48982407-02d47f80-f0f3-11e8-9cff-56d270edbd23.jpg)
![2](https://user-images.githubusercontent.com/32225962/48982408-036d1600-f0f3-11e8-985d-b84fb1d9ce14.jpg)

2018-11-26 09:28 UTC, Qmannn approved these changes
Отлично! Теперь нужно сделать Rebase и объединить коммиты в один (Squash) а затем можно смержить и закрыть задачу с комментарием и скрином что было сделано

2018-11-27 06:18 UTC, CaptainGlobers approved these changes

2018-11-27 09:12 UTC, merged