Добавил страницу "Список пользователей"
Qmannn/food-service pull request #40
Opened 2018-10-31 16:36 UTC by glcherepanov

2018-10-31 19:50 UTC, Qmannn requested changes

2018-10-31 19:50 UTC, Qmannn commented on FoodAdmin/Controllers/UserController.cs
> +    public class UserController : Controller
Давай поправим UserController на User**s**Controller
UserController - в нашем подходе это скорее будет контроллер для страницы редактирования пользователя

2018-10-31 19:50 UTC, Qmannn commented on FoodAdmin/Controllers/UserController.cs
> +        [HttpGet("users")]
Поскольку api называется api/users можно оставить роут для HttpGet пустым `[HttpGet("")]`, тогда обратиться к этому методу можно по адресу GET api/users

2018-11-02 13:45 UTC, glcherepanov commented on FoodAdmin/Controllers/UserController.cs
> +    public class UserController : Controller
Сделал

2018-11-02 13:45 UTC, glcherepanov commented on FoodAdmin/Controllers/UserController.cs
> +        [HttpGet("users")]
Сделал

2018-11-06 05:36 UTC, Qmannn approved these changes

2018-11-07 09:26 UTC, CaptainGlobers commented
задачу можно слить

2018-11-07 09:29 UTC, merged