Добавление страницы добавления пользователя #34
Qmannn/food-service pull request #44
Opened 2018-11-16 11:02 UTC by ondrosru

2018-11-16 11:03 UTC, ondrosru commented
Исправил замечания о именовании файлов

2018-11-19 07:56 UTC, Qmannn requested changes

2018-11-19 07:56 UTC, Qmannn commented on FoodAdmin/ClientApp/src/HttpServices/EditUserDataService.js
> +"use strict";
Этот файл комитить не нужно

2018-11-19 07:56 UTC, Qmannn commented on FoodAdmin/ClientApp/src/HttpServices/EditUserDataService.js.map
> +{"version":3,"file":"UserDataService.js","sourceRoot":"","sources":["UserDataService.ts"],"names":[],"mappings":""}
Этот файл комитить не нужно

Нужно откатить изменения в нем

2018-11-19 07:56 UTC, Qmannn commented on FoodAdmin/Controllers/EditUserController.cs
> +        public SavedNewUser AddUser([FromBody] UserDto newUser)
Давай назовем SaveUser чтобы избавить от конкретики добавления. Потом этот метод будем использовать и для редактирования пользователя

2018-11-19 07:56 UTC, Qmannn commented on FoodAdmin/Controllers/SampleController.cs
>      public class SampleController : Controller
В этом файле все изменения надо откатить

2018-11-19 07:56 UTC, Qmannn commented on FoodAdmin/Dto/Sample/SampleDto.cs
> +    public class UserDto
Изменения надо отменить

2018-11-19 07:56 UTC, Qmannn commented on FoodAdmin/ClientApp/src/app.module.ts
> +      { path: 'add-user', component: EditUserComponent },
edit-user так потом проще будет

2018-11-19 07:56 UTC, Qmannn commented on FoodAdmin/ClientApp/src/components/pages/EditUser/EditUser.Component.ts
> +  // selector: 'app-add-user',
комментарий надо бы удалитб

2018-11-19 07:56 UTC, Qmannn commented on FoodAdmin/ClientApp/src/dto/User/SavedNewUser.js
> +"use strict";
Эти файлы не нужно было коммитить

2018-11-19 07:56 UTC, Qmannn commented on FoodAdmin/ClientApp/src/dto/User/SavedNewUser.js.map
> +{"version":3,"file":"SavedNewUser.js","sourceRoot":"","sources":["SavedNewUser.ts"],"names":[],"mappings":";;AAAA;IAAA;IAIA,CAAC;IAAD,sBAAC;AAAD,CAAC,AAJD,IAIC;AAJY,0CAAe"}
Это файл тоже не нужно коммитить

2018-11-19 07:56 UTC, Qmannn commented on FoodAdmin/ClientApp/src/dto/User/UserDto.js
> +"use strict";
Файл не нужно коммитить

2018-11-19 07:56 UTC, Qmannn commented on FoodAdmin/ClientApp/src/dto/User/UserDto.js.map
> +{"version":3,"file":"UserDto.js","sourceRoot":"","sources":["UserDto.ts"],"names":[],"mappings":";;AAAA;IAAA;IAIA,CAAC;IAAD,cAAC;AAAD,CAAC,AAJD,IAIC;AAJY,0BAAO"}
Файл не нужно коммитить

2018-11-19 07:56 UTC, Qmannn commented on FoodAdmin/Dto/User/SavedNewUser.cs
> +    public class SavedNewUser
Давай назовем класс SavedUserDto
1) Чтобы использовать потом для редактирования этот же класс
2) Dto всегда добавляем к названиям контрактов между клиентом и сервером

2018-11-19 07:56 UTC, Qmannn commented on FoodAdmin/Dto/User/SavedNewUser.cs
> +        public int SavedId { get; set; }
Давай избавимся от приставки Saved
Сделаем поля UserId, UserName, Name

2018-11-19 07:56 UTC, Qmannn commented on FoodAdmin/Dto/User/SavedNewUser.cs
> +        public int SavedId { get; set; }
На самом деле можно даже избавиться от этого класса и использовать UserDto так как там такие же свойства

2018-11-19 07:56 UTC, Qmannn commented on FoodAdmin/FoodAdmin.csproj
> +    <TypeScriptCompile Include="ClientApp\src\components\pages\EditUser\EditUser.Component.ts" />
Как вышло, что теперь студия сама собирает TypeScript файлы? Надо эти изменения откатить. Мы собираем с помощью angular cli (ng)
Чтобы  это откатить достаточно удалить в файле строки 36 - 42 и строки 29-32

2018-11-23 13:32 UTC, ondrosru commented
Исправил ошибки

2018-11-26 09:33 UTC, Qmannn requested changes

2018-11-26 09:33 UTC, Qmannn commented on .gitignore
> +FoodAdmin/ClientApp/src/HttpServices/EditUserDataService.js.rej
Эти две строчки можно удалить, они пересекаются со строчками ниже

2018-11-26 09:40 UTC, Qmannn requested changes

2018-11-26 09:40 UTC, Qmannn commented on FoodAdmin/Dto/User/SavedUserDto.cs
> +    public class SavedUserDto
Можно заметить, что SavedUserDto и UserDto один в один похожи. Давай удалим SavedUserDto и будем использовать только UserDto, так будет проще

2018-11-26 09:40 UTC, Qmannn commented on FoodAdmin/ClientApp/src/environments/environment.ts
> +  baseUrl: 'http://localhost:50308/'
Нужно вернуть порт 55222 а в параметрах запуска указать такие параметры
![image](https://user-images.githubusercontent.com/10262301/49005523-f6463a80-f177-11e8-91da-53c152a18b0a.png)

2018-11-26 09:40 UTC, Qmannn commented on FoodAdmin/Controllers/EditUserController.cs
> +                Name = $"",
Знак $ тут не нужен. Он позволяет использовать интерполяцию строк. Отсюда можно удалить ну и желательно почитать про этот оператор и про интерполяцию. Вот хорошая статья [metanit.com/](https://metanit.com/sharp/tutorial/7.5.php)

2018-11-26 11:10 UTC, ondrosru commented on .gitignore
> +FoodAdmin/ClientApp/src/HttpServices/EditUserDataService.js.rej
удалил

2018-11-26 11:10 UTC, ondrosru commented on FoodAdmin/Dto/User/SavedUserDto.cs
> +    public class SavedUserDto
удалил SavedUserDto

2018-11-26 11:11 UTC, ondrosru commented on FoodAdmin/ClientApp/src/environments/environment.ts
> +  baseUrl: 'http://localhost:50308/'
Вернул порт, поменял параметры запуска

2018-11-26 11:11 UTC, ondrosru commented on FoodAdmin/Controllers/EditUserController.cs
> +                Name = $"",
Удалил $

2018-11-26 12:15 UTC, Qmannn requested changes
Нужно удалить все файлы .js и .js,map.
И посмотреть все комментарии начиная с самого первого в этом пулреквесте. По каждому нужно проверить, что доработки внесены и отписать что сделано.

2018-11-26 12:15 UTC, Qmannn commented on FoodAdmin/ClientApp/src/dto/User/SavedUserDto.ts
> +export class SavedUserDto {
Раз удален SavedUserDto надо и этот класс удалить

2018-11-27 14:37 UTC, ondrosru commented on FoodAdmin/ClientApp/src/dto/User/SavedUserDto.ts
> +export class SavedUserDto {
Удалены лишние js файлы отмеченные сверху. Ревернут simpleDto и simpleControler. Удалены лишние SavedUserDto. Исправлены параметры запуска. Удалена сборка ts самой студией.

2018-11-27 14:37 UTC, ondrosru commented
Удалены лишние js файлы отмеченные сверху. Ревернут simpleDto и simpleControler. Удалены лишние SavedUserDto. Исправлены параметры запуска. Удалена сборка ts самой студией.

2018-11-27 14:38 UTC, ondrosru commented
Удалил $ в EditUserList

2018-11-27 16:54 UTC, ondrosru commented on FoodAdmin/ClientApp/src/HttpServices/EditUserDataService.js
> +"use strict";
Удалил файл

2018-11-27 16:54 UTC, ondrosru commented on FoodAdmin/ClientApp/src/HttpServices/EditUserDataService.js.map
> +{"version":3,"file":"UserDataService.js","sourceRoot":"","sources":["UserDataService.ts"],"names":[],"mappings":""}
Удалил файл

2018-11-27 16:55 UTC, ondrosru commented on FoodAdmin/Controllers/SampleController.cs
>      public class SampleController : Controller
Откатил файл

2018-11-27 16:56 UTC, ondrosru commented on FoodAdmin/Dto/Sample/SampleDto.cs
> +    public class UserDto
Откатил файл

2018-11-27 16:56 UTC, ondrosru commented on FoodAdmin/Controllers/EditUserController.cs
> +        public SavedNewUser AddUser([FromBody] UserDto newUser)
Переименовал addUser в SaveUser

2018-11-27 16:57 UTC, ondrosru commented on FoodAdmin/ClientApp/src/dto/User/UserDto.js
> +"use strict";
Удалил файл

2018-11-27 16:57 UTC, ondrosru commented on FoodAdmin/ClientApp/src/dto/User/UserDto.js.map
> +{"version":3,"file":"UserDto.js","sourceRoot":"","sources":["UserDto.ts"],"names":[],"mappings":";;AAAA;IAAA;IAIA,CAAC;IAAD,cAAC;AAAD,CAAC,AAJD,IAIC;AAJY,0BAAO"}
Удалил

2018-11-27 16:58 UTC, ondrosru commented on FoodAdmin/Dto/User/SavedNewUser.cs
> +    public class SavedNewUser
Удали. Вместо него использую UserDto

2018-11-27 16:59 UTC, ondrosru commented on FoodAdmin/Dto/User/SavedNewUser.cs
> +        public int SavedId { get; set; }
Избавился от этого класса

2018-11-27 16:59 UTC, ondrosru commented on FoodAdmin/FoodAdmin.csproj
> +    <TypeScriptCompile Include="ClientApp\src\components\pages\EditUser\EditUser.Component.ts" />
Удалил отмеченные стоки кода

2018-11-27 20:48 UTC, Qmannn approved these changes
Теперь нужно сделать rebase и объединить коммиты, а затем смержить

2018-11-30 07:02 UTC, Qmannn commented
Пулреквест прежде чем закрывать необходимо смержить

2018-12-01 12:18 UTC, merged