Создала страницу добавления блюда
Qmannn/food-service pull request #45
Opened 2018-11-27 17:00 UTC by AnastasiaBastrakova

2018-11-27 20:39 UTC, Qmannn requested changes

2018-11-27 20:39 UTC, Qmannn commented on FoodAdmin/ClientApp/src/index.html
> +  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
Вместо такого добавления jquery, лучше установить его в проект с помощью менеджера пакетов npm
для этого нужно в консоли в папке ClientApp выполнить команду `npm install jquery` таким образом пакет будет добавлен и при следующей сборке он добавится в файл vendor.bundle.js и появится возможность его использовтаь.  Отсюда строчку можно удалить будет.
На следующем занятии продемонстрируем работу  с менеджером пакетов.

2018-11-27 20:39 UTC, Qmannn commented on FoodAdmin/ClientApp/src/styles.css
> +
Изменений в файле фактически нет, надо бы откатить добавленную строку

2018-11-27 20:39 UTC, Qmannn commented on FoodAdmin/Controllers/SampleController.cs
> +
Изменения надо откатить. Любое изменение, не относящееся к добавляемому или изменяемому в задаче не должно попадать в пулреквест

2018-11-27 20:39 UTC, Qmannn commented on FoodAdmin/Dto/Dish/DishDto.cs
> +    public class DishDto
DishDto полностью аналогичен SavedDishDto, лучше отсавить один класс и его использовтаь.
Как тут, так и на фронтенде

2018-11-27 20:39 UTC, Qmannn commented on FoodAdmin/FoodAdmin.csproj
> +  </ItemGroup>
Эти строки так же надо откатить

2018-11-27 20:39 UTC, Qmannn commented on FoodAdmin/Service/DishService.cs
> +            }
Вместо конструкции с if можно использовтаь оператор ??
Он позволяет взять либо левый параметр если он не null либо правый иначе.
`Dish dish = _dishRepository.GetItem(dishDto.DishId) ?? new Dish();`

2018-11-27 20:39 UTC, Qmannn commented on FoodAdmin/ClientApp/src/dto/Dish/SavedDishInfo.ts
> +enum DishCategory {
Enum надо бы вынести в отдельный файл

2018-11-27 20:39 UTC, Qmannn commented on FoodAdmin/ClientApp/src/dto/Dish/DishDto.ts
> +export enum DishCategory {
Enum один в один как в файле SavedDishInfo.ts, такого лучше не делать, чтобы потом не запутаться.

2018-11-27 20:39 UTC, Qmannn commented on FoodAdmin/ClientApp/src/components/pages/Dish/Dish.component.ts
> +  public dishCategories: Array<any> = [
1) Давай вынесем получение этого массива в отдельный класс DishCategoryNameUtil в метод GetCategories();
2) any использовать не нужно, это не лучшая практика поскольку поддержка такого кода очень сложна в конечном итоге. Нужно описать класс, который необходим. Здесь, например, напрашивается класс SelectOption, описывающий опцию в Select, класс должен иметь два свойства value и name.
А метод GetCategories(); будет возвращать SelectOption[]
К тому же SelectOption в дальнейшем можно будет переиспользовать для других контролов Select, очень удобно будет.

2018-11-27 20:39 UTC, Qmannn commented on FoodAdmin/ClientApp/src/components/pages/Dish/Dish.component.ts
> +    this.dishToEdit.containerId = 1;
вместо инициализации блюда в конструкторе, лучше получить блюдо с бекенда.
Таким образом можно обойти разные реализации для создания и редактирования и использовать один функционал.

2018-11-27 20:41 UTC, Qmannn commented
Здорово, что сделала сразу и работу с базой данных, однако, в следующий раз лучше бы такое разделить на два пулреквеста, чтобы было проще смотреть. Чем меньше функционала - тем быстрее пулреквест сливается.

2018-11-28 11:43 UTC, AnastasiaBastrakova commented on FoodAdmin/ClientApp/src/index.html
> +  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
На самом деле я обошлась без jqery, использовала select. Просто удалила строчку из index.html, если потом понадобится jqery - подключу через консоль.

2018-11-29 13:58 UTC, CaptainGlobers commented on FoodAdmin/ClientApp/src/components/pages/Dish/Dish.component.ts
> +    this.dishToEdit.containerId = 1;
получить с back-end блюдо при создании блюда?

2019-01-17 11:37 UTC, AnastasiaBastrakova commented on FoodAdmin/ClientApp/src/components/pages/Dish/Dish.component.ts
> +    this.dishToEdit.containerId = 1;
сделала

2019-01-17 15:24 UTC, AnastasiaKatelinskaya commented on FoodAdmin/ClientApp/src/components/pages/Dish/Dish.component.ts
> +  public dishCategories: Array<any> = [
Готово

2019-01-17 15:25 UTC, AnastasiaBastrakova commented on FoodAdmin/ClientApp/src/dto/Dish/DishDto.ts
> +export enum DishCategory {
готово

2019-01-17 15:25 UTC, AnastasiaBastrakova commented on FoodAdmin/ClientApp/src/dto/Dish/SavedDishInfo.ts
> +enum DishCategory {
готово

2019-01-17 15:32 UTC, AnastasiaBastrakova commented on FoodAdmin/Service/DishService.cs
> +            }
готово

2019-01-17 16:37 UTC, AnastasiaBastrakova commented on FoodAdmin/ClientApp/src/styles.css
> +
оставили как есть

2019-01-17 16:37 UTC, AnastasiaBastrakova commented on FoodAdmin/Controllers/SampleController.cs
> +
оставили как есть

2019-01-17 16:37 UTC, AnastasiaBastrakova commented on FoodAdmin/Dto/Dish/DishDto.cs
> +    public class DishDto
сделала

2019-01-17 16:37 UTC, AnastasiaBastrakova commented on FoodAdmin/FoodAdmin.csproj
> +  </ItemGroup>
удалила

2019-01-17 16:39 UTC, Qmannn approved these changes

2019-01-17 16:40 UTC, merged