Реализовал получение списка пользователей из БД
Qmannn/food-service pull request #48
Opened 2018-12-06 12:40 UTC by glcherepanov

2018-12-08 18:17 UTC, Qmannn requested changes

2018-12-08 18:17 UTC, Qmannn commented on FoodAdmin/Controllers/UserController.cs
>              return new List<UserDto>
Заглушку можно удалить. В примере я сделал так просто для того, чтобы хоть что-то отображалось. Здесь же если пользователей нет - лучше не показывать ничего

2018-12-08 18:17 UTC, Qmannn commented on FoodAdmin/Controllers/UserController.cs
> +                    Role = Food.EntityFramework.Entities.Enums.UserRole.Administrator
Вместо того, чтобы писать полный namespace лучше указать его в using

using Food.EntityFramework.Entities.Enums; вверху страницы. Студия вроде умеет это делать автоматически

2018-12-14 19:30 UTC, glcherepanov commented on FoodAdmin/Controllers/UserController.cs
>              return new List<UserDto>
Сделал.

2018-12-14 19:33 UTC, glcherepanov commented on FoodAdmin/Controllers/UserController.cs
> +                    Role = Food.EntityFramework.Entities.Enums.UserRole.Administrator
Пропробовал, работает, убрал тестовые данные т.к. выводит их больше не нужно.

2018-12-20 08:46 UTC, Qmannn approved these changes
Можно внести правки по комментам и сливать
(не забудь объединить коммиты в один)

2018-12-20 08:46 UTC, Qmannn commented on FoodAdmin/Controllers/UserController.cs
> +            var storedUsers = _usersService.GetUsers();
В принципе, можно не объявлять переменную, а простовернуть результат метода GetUsers() так будет короче

2018-12-25 14:02 UTC, merged