Issue 42 add comands management
Qmannn/food-service pull request #49
Opened 2018-12-08 11:35 UTC by Just-D-A

Add commands management

2018-12-08 12:30 UTC, Qmannn requested changes
Нужно внести правки и отписать по сделанному под КАЖДЫМ комментарием.

2018-12-08 12:30 UTC, Qmannn commented on FoodAdmin/ClientApp/src/dto/Commands/CommandsDto.ts
> +export class CommandsDto {
По всему коду изменений фигурирует название Commands, это слово - множественное число, дословно "Команды", сущность должна называться "Команда" Command так как описывает только один экземпляр команды. Классы очень редко называются во множетсвенном числе, обычно в единственном.
class Command{}

`Command command = new Command();`
`List<Command> commands = new List<Commands>() `-вот тут множественное число поскольку переменная является списком команд, поэтому команы

Нужно по всему пулреквесту поправить Commands там где это единсвенное число на Comand

2018-12-08 12:30 UTC, Qmannn commented on Food.EntityFramework/Entities/Commands.cs
> +    public class Commands: IEntity
Зачем был добавлен этот файл? Пока, думаю, он не нужен.
Это описание сущности в базе. Нужно удалить.

2018-12-08 12:30 UTC, Qmannn commented on FoodAdmin/ClientApp/src/components/pages/Commands/Commands.Component.ts
> +    this._commandsDataService.getCommands().subscribe(values => {
values надо переименовать в название того, что приходит в этот метод.
Название переменной должно описывать то, что в ней находится

2018-12-08 12:30 UTC, Qmannn commented on FoodAdmin/ClientApp/src/dto/Commands/SavedCommandsInfo.ts
> +export class SavedCommandsInfo {
SavedCommandsInfo -> SavedCommandInfo 
В единственном числе должно быть

2018-12-08 12:30 UTC, Qmannn commented on FoodAdmin/Controllers/CommandsController.cs
> +        public List<CommandsDto> GetUsers()
GetUsers - надо переименовать, туь возвращается не список пользователей

2018-12-08 12:30 UTC, Qmannn commented on FoodAdmin/Dto/Commands/CommandsDto.cs
> +    public class CommandsDto
Переименовать нужно

2018-12-08 12:30 UTC, Qmannn commented on FoodAdmin/Dto/Commands/CommandsDto.cs
> +        public int CommandsId { get; set; }
CommandsId = "Идентификаторы команд"
Должно быть "Идентификатор команды"
Т.е. В единсвенном числе быть должно. Надо поправть

2018-12-08 12:53 UTC, Just-D-A commented on FoodAdmin/ClientApp/src/dto/Commands/CommandsDto.ts
> +export class CommandsDto {
Хорошо, начинаю исправлять

2018-12-08 13:50 UTC, Just-D-A commented on FoodAdmin/ClientApp/src/dto/Commands/CommandsDto.ts
> +export class CommandsDto {
Переименовал "commands" -> "command"
Залил в ветку

2018-12-08 18:13 UTC, Qmannn requested changes

2018-12-08 18:13 UTC, Qmannn commented on FoodAdmin/ClientApp/src/components/pages/Command/Commands.Component.ts
> +  public command: CommandDto[];
Поскольку это массив - правильнее назвать commands

2018-12-08 18:13 UTC, Qmannn commented on FoodAdmin/Controllers/CommandController.cs
> +                    Description = "���������� ������ �������"
что-то с кодировкой файла. Надо сделать utf8

2018-12-08 18:13 UTC, Qmannn commented on FoodAdmin/Controllers/CommandController.cs
> +        public List<CommandDto> GetCommand()
Метод возвращает массив, поэтому называть его нужно GetCommands

2018-12-08 18:13 UTC, Qmannn commented on FoodAdmin/FoodAdmin.csproj
> +    <Content Remove="ClientApp\src\dto\����� �����\**" />
Изменений в этом файле быть не должно. Надо откатить

2018-12-08 19:51 UTC, Just-D-A commented on Food.EntityFramework/Entities/Commands.cs
> +    public class Commands: IEntity
Удаляю

2018-12-08 20:12 UTC, Just-D-A commented on FoodAdmin/ClientApp/src/components/pages/Commands/Commands.Component.ts
> +    this._commandsDataService.getCommands().subscribe(values => {
"values" -> "commands"

2018-12-08 20:14 UTC, Just-D-A commented on FoodAdmin/ClientApp/src/dto/Commands/SavedCommandsInfo.ts
> +export class SavedCommandsInfo {
Было сделано верно изначально, как залью проконтролирую

2018-12-08 20:23 UTC, Just-D-A commented on FoodAdmin/ClientApp/src/components/pages/Commands/Commands.Component.ts
> +    this._commandsDataService.getCommands().subscribe(values => {
"values" -> "commandsValues"

2018-12-08 20:25 UTC, Just-D-A commented on FoodAdmin/ClientApp/src/dto/Commands/SavedCommandsInfo.ts
> +export class SavedCommandsInfo {
Исправлено

2018-12-08 20:26 UTC, Just-D-A commented on FoodAdmin/Controllers/CommandsController.cs
> +        public List<CommandsDto> GetUsers()
Исправлено

2018-12-08 20:26 UTC, Just-D-A commented on FoodAdmin/Dto/Commands/CommandsDto.cs
> +    public class CommandsDto
Исправлено

2018-12-08 20:26 UTC, Just-D-A commented on FoodAdmin/Dto/Commands/CommandsDto.cs
> +        public int CommandsId { get; set; }
Исправлено

2018-12-08 20:27 UTC, Just-D-A commented on FoodAdmin/ClientApp/src/components/pages/Command/Commands.Component.ts
> +  public command: CommandDto[];
Исправлено

2018-12-08 20:39 UTC, Just-D-A commented on FoodAdmin/Controllers/CommandController.cs
> +                    Description = "���������� ������ �������"
![encodingfiles](https://user-images.githubusercontent.com/32079550/49690459-712d2f00-fb42-11e8-9550-94f06aba5600.png)
Тут??

2018-12-08 21:13 UTC, Just-D-A commented on FoodAdmin/Controllers/CommandController.cs
> +        public List<CommandDto> GetCommand()
Изменил на GetCommands

2018-12-08 21:31 UTC, Just-D-A commented on FoodAdmin/FoodAdmin.csproj
> +    <Content Remove="ClientApp\src\dto\����� �����\**" />
Не могу разобраться с этим

2018-12-08 21:39 UTC, Just-D-A commented on FoodAdmin/FoodAdmin.csproj
> +    <Content Remove="ClientApp\src\dto\����� �����\**" />
![default](https://user-images.githubusercontent.com/32079550/49691011-d7b64b00-fb4a-11e8-9b68-fc7cd1dcb20a.png)

2018-12-09 21:27 UTC, Just-D-A commented on FoodAdmin/Controllers/CommandController.cs
> +                    Description = "���������� ������ �������"
Исправил

2018-12-13 14:10 UTC, Qmannn approved these changes

2018-12-13 14:10 UTC, Qmannn commented on FoodAdmin/FoodAdmin.csproj
> +    <Content Remove="ClientApp\src\dto\����� �����\**" />
На коммите в логе нужно нажать "Revert changes by this commit" затем в diff сделать Revert для всех файлов кроме этого и закоммитить

2018-12-14 18:06 UTC, merged