ISSUE-56 Добавление карточки блюда
Qmannn/food-service pull request #58
Opened 2019-01-30 14:40 UTC by ondrosru

для просмотра вставки компонента /dish-card

2019-01-30 17:04 UTC, Qmannn requested changes

2019-01-30 17:04 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DishCard/DishCard.Component.css
> +    height: 100px;
Давай сделаем углы более скругленными, до 5 пикселей поднимем радиус
Еще margin желательно в оболочке компонента не использовать, поскольку потом тому, кто использует компонент будет неудобно регулировать его положение. margin будет всегда смещать его.  Чтобы карточку было видно на странице предпросмотра, которую ты сделал, добавь отступ там для тега компонента.

2019-01-30 17:04 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DishCard/DishCard.Component.css
> +    height: 100px;
Тело карточки хорошо бы сместить ближе к центру по вертикали, примерно на 10 пикселей.

2019-01-30 17:04 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DishCard/DishCard.Component.html
> +        <p class="card-title">Название{{dish.name}}</p>
Тут слово "Название" так-то не обязательно, поскольку name всегда должно быть.
Надо обработать ситуацию, когда dish = undefined.

2019-01-30 17:04 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DishCard/DishCard.Component.css
> +}
Самая последняя строка в файле всегда должна быть пустой. добавь перенос строки тут и во всех остальных файлах

2019-01-30 17:04 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DishCard/DishCard.Component.ts
> +import { Component, Input } from "@angular/core";
Мы в UI коде используем одинарные кавычки везде. Если будешь редактировать в VS Code она тебе даже подсветит это как ошибки.
Надо бы поправить тут и во всех других файлах

2019-01-30 17:04 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DishCard/DishCard.Component.ts
> +
Лишний перенос строки

2019-01-30 17:04 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DishCard/DishSimple.Component.ts
> +    //selector: 'app-simple',
На самом деле это просто комментарий, можно его удалить, это никак не повлияет на функциональность.

2019-02-06 13:55 UTC, ondrosru commented on FoodService/ClientApp/src/app/Components/DishCard/DishSimple.Component.ts
> +    //selector: 'app-simple',
Удалил локально

2019-02-06 13:56 UTC, ondrosru commented on FoodService/ClientApp/src/app/Components/DishCard/DishCard.Component.ts
> +
Удалил лишний перенос строки

2019-02-06 13:56 UTC, ondrosru commented on FoodService/ClientApp/src/app/Components/DishCard/DishCard.Component.ts
> +import { Component, Input } from "@angular/core";
поменял кавычки

2019-02-06 13:57 UTC, ondrosru commented on FoodService/ClientApp/src/app/Components/DishCard/DishCard.Component.css
> +    height: 100px;
Поставил значение border-radius на 5px

2019-02-06 13:57 UTC, ondrosru commented on FoodService/ClientApp/src/app/Components/DishCard/DishCard.Component.css
> +    height: 100px;
Не уверен сделал через padding отсуп по 10 px

2019-02-07 07:19 UTC, ondrosru commented on FoodService/ClientApp/src/app/Components/DishCard/DishCard.Component.css
> +    height: 100px;
Убрал margin.

2019-02-07 11:00 UTC, ondrosru commented on FoodService/ClientApp/src/app/Components/DishCard/DishCard.Component.css
> +}
Сделал

2019-02-07 11:00 UTC, ondrosru commented on FoodService/ClientApp/src/app/Components/DishCard/DishCard.Component.html
> +        <p class="card-title">Название{{dish.name}}</p>
Удалил слово название

2019-02-13 11:48 UTC, Qmannn approved these changes

2019-02-13 11:56 UTC, merged