Add column
Qmannn/food-service pull request #61
Opened 2019-02-15 07:39 UTC by kvladiimiir

2019-02-18 07:57 UTC, Qmannn requested changes

2019-02-18 07:57 UTC, Qmannn commented on FoodService/FoodService.csproj
> +  </ItemGroup>
4 строки выше нужно удалить

2019-02-18 07:57 UTC, Qmannn commented on FoodService/FoodService.csproj
> +    <None Remove="ClientApp\src\dto\Dish\DishDto.ts" />
Добавленные выше строки можно удалить

2019-02-18 07:57 UTC, Qmannn commented on FoodService/FoodService.csproj
> +    <Content Remove="ClientApp\src\app\Components\ColumnForDishes\**" />
В этом файле можно откатить изменения совсем. Без них должно работать

2019-02-18 18:52 UTC, kvladiimiir commented on FoodService/FoodService.csproj
> +    <Content Remove="ClientApp\src\app\Components\ColumnForDishes\**" />
откатил изменения

2019-02-18 21:00 UTC, kvladiimiir commented on FoodService/FoodService.csproj
> +    <Content Remove="ClientApp\src\app\Components\ColumnForDishes\**" />
сделал revert FoodService.csproj

2019-02-21 10:19 UTC, kvladiimiir commented on FoodService/FoodService.csproj
> +  </ItemGroup>
сделал реверт , поэтому эти строки были удалены

2019-02-21 10:19 UTC, kvladiimiir commented on FoodService/FoodService.csproj
> +    <None Remove="ClientApp\src\dto\Dish\DishDto.ts" />
сделал реверт, этих строк больше там нет

2019-02-21 10:26 UTC, Qmannn approved these changes
Нужно удалить страницу примера и объединить коммиты в один, затем можно сливать

2019-02-21 10:26 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DishColumns/DishColumnsSample.Component.ts
> +  selector: 'app-dish-columns-sample',
Давай оставим пример только на станице counter, этот пример удалим.
Чтобы потом не образовалось много хвостов, которые нужно чистить

2019-02-23 09:46 UTC, merged

2019-02-23 09:49 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DishColumns/DishColumnsSample.Component.ts
> +  selector: 'app-dish-columns-sample',
сделал