Issue-60 Соединила страницы "Добавить/Изменить блюдо" и "Список блюд"
Qmannn/food-service pull request #63
Opened 2019-02-21 09:27 UTC by AnastasiaBastrakova

2019-03-07 23:46 UTC, Qmannn requested changes
1) Пункты меню подсвечивать в зависимости от контекста пользователя:
Список блюд + редактирование блюда: подсвечиваем путь "Список блюд". Для наглядности можно пункт меню переименовать в "Блюда"

Так же с пользователями: список + редактирование/создание
.
Лишние страницы нужно удалить
![image](https://user-images.githubusercontent.com/10262301/53997232-6c314900-414c-11e9-8926-8c63ef1f0e11.png)

2019-03-07 23:46 UTC, Qmannn commented on FoodAdmin/ClientApp/src/app.module.ts
> +      { path: 'dish-list', component: DishListComponent, pathMatch: 'full' },
При таком подходе на странице редактирования блюда не будет выделен пункт меню "Список блюд".
Поскольку пользователь находится в том же контексте необходимо реализовтаь выделение пункта меню так же как на странице примера

![image](https://user-images.githubusercontent.com/10262301/53997022-aa7a3880-414b-11e9-9a46-2490d1ed9544.png)

При редактировании и создании выглядит так:
![image](https://user-images.githubusercontent.com/10262301/53997046-c1b92600-414b-11e9-95af-97e2dc4c6d9e.png)

Так работает за счет того, что путь до страницы составной.
Пункт меню активируется если путь начинается на sample
Страница списка имеет путь sample
Страница редактирования путь sample/edit-sample

Такую же историю нужно со всеми страницами сделать.

2019-04-08 19:37 UTC, AnastasiaBastrakova commented on FoodAdmin/ClientApp/src/app.module.ts
> +      { path: 'dish-list', component: DishListComponent, pathMatch: 'full' },
Поправила

2019-04-10 13:48 UTC, Qmannn approved these changes

2019-04-10 13:48 UTC, Qmannn commented on FoodAdmin/ClientApp/src/environments/environment.ts
> +  baseUrl: 'http://localhost:57115/'
тут нужно вернуть 55222. 
Чтобы проект работал менять порт нужно в launchSettings.json

2019-04-10 13:48 UTC, Qmannn commented on FoodAdmin/Controllers/DishController.cs
> +            return storedDishes;
return  _dishService.GetDishes();

2019-04-10 14:22 UTC, AnastasiaBastrakova commented on FoodAdmin/ClientApp/src/environments/environment.ts
> +  baseUrl: 'http://localhost:57115/'
Поменяла

2019-04-10 14:30 UTC, AnastasiaBastrakova commented on FoodAdmin/Controllers/DishController.cs
> +            return storedDishes;
Сделала

2019-04-10 14:34 UTC, merged