Issue 64 date picker
Qmannn/food-service pull request #69
Opened 2019-03-12 17:11 UTC by CaptainGlobers

2019-03-13 10:07 UTC, CaptainGlobers commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public getMonth(month): string {
Функционал работы с датами лучше вынести в отдельный класс например DateHelper.ts

2019-03-13 10:07 UTC, CaptainGlobers commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public getWeekDay(weekDay): string {
Функционал работы с датами лучше вынести в отдельный класс например DateHelper.ts

2019-03-13 10:07 UTC, CaptainGlobers commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public count: number = 1;
для чего count?

2019-03-13 10:07 UTC, CaptainGlobers commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public addDay(day: Date, counter: number): void {
данную функцию я скинул для примера, в твоем случае лучше использовать немного другую реализацию
например:   
  public addDay(day: Date, incrementDays: number): Date {
    return new Date(day.getFullYear(), day.getMonth(), day.getDate() + incrementDays);
  }

2019-03-13 10:07 UTC, CaptainGlobers commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public weekDays = [this.weekDay, this.weekDay + 1, this.weekDay + 2, this.weekDay + 3, this.weekDay + 4, this.weekDay + 5];
в данном случае думаю стоит сразу использовать массив дней:
  private fillWeekDays(): Date[] {
    const result: Date[] = [];
    const now: Date = new Date;
    for(let i: number = 0; i < 7; i++) {
      const weekDay: Date = this.addDay(now, i);
      result.push(weekDay);
    }
    
    return result;
  }

  public weekDays: Date[] = this.fillWeekDays();

2019-03-13 10:07 UTC, CaptainGlobers commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public getWeekDay(weekDay): string {
лучше что бы функция принимала в качестве аргумента Date

2019-03-13 10:07 UTC, CaptainGlobers commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public getMonth(month): string {
лучше что бы функция принимала в качестве аргумента Date

2019-03-15 19:59 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public weekDays = [this.weekDay, this.weekDay + 1, this.weekDay + 2, this.weekDay + 3, this.weekDay + 4, this.weekDay + 5];
сделал

2019-03-15 20:00 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public addDay(day: Date, counter: number): void {
сделал

2019-03-15 20:01 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public count: number = 1;
удалил, так как теперь есть i-ый элемент и с ним удобнее работать

2019-03-16 11:24 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public getWeekDay(weekDay): string {
сделал

2019-03-16 11:24 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public getMonth(month): string {
сделал

2019-03-16 15:39 UTC, CaptainGlobers commented on FoodService/ClientApp/src/app/counter/counter.component.html
> +  <app-date-picker></app-date-picker>
тут не хватает эмитера как тут в 16 строчке (counter.component.html)
<<... (dateSelected)="deselectDate($event)" ...>>
пример реализации есть в DishColumns.Component.ts

2019-03-24 11:02 UTC, Qmannn requested changes

2019-03-24 11:02 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public workDate: WorkDate = new WorkDate();
Свойство использутеся только в UI самого контрола, поэтому необходимо модификтор protected вместо public

2019-03-24 11:02 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public weekDays: Date[] = this.workDate.fillWeekDays();
1) protected
2) Согласно стилям кодирования необходимо публичные свойства (переменные) помещать выше чем методы, т.е. нужно перенести свойство на строку 12

2019-03-24 11:02 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public weekDays: Date[] = this.workDate.fillWeekDays();
Это поможет сгруппировать вместе методы и свойства для лучшей читаемости

2019-03-24 11:02 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +    return day == this.selectedDate ? 'selected-date' : '';
в ts необходимо использовтаь знак строгого равенства ===

2019-03-24 11:02 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DatePicker/WorkDate.ts
> +  public getMonthString(month): string {
Давай вместо цифр заведем enum с названиями всех месяцев
```
public enum Month {
    January = 0,
    February = 1,
    ...
}
```

2019-03-24 11:02 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DatePicker/WorkDate.ts
> +    switch (dayInWeek) {
По аналогии с месяцами лучше добавить Enum.

2019-03-24 11:02 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DatePicker/WorkDate.ts
> +  public getMonthString(month): string {
По факту из UI в метод будет передаваться все та же цифра, но в коде будет выглядеть как enum/
Так повышается читаемость

2019-03-24 11:02 UTC, Qmannn commented on FoodService/ClientApp/src/app/app.module.ts
> +      { path: 'dish-card', component: DishSimpleComponent },
DishSimpleComponent - такого компонента нет, тут должен быть DishCardComponent наверно

2019-03-24 11:02 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DatePicker/WorkDate.ts
> +  public weekDayString(dayInWeek): string {
не указан тип входного параметра

2019-03-24 11:02 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DatePicker/WorkDate.ts
> +  public getMonthString(month): string {
Не указан тип входного параметра

2019-03-24 11:02 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DatePicker/WorkDate.ts
> +    for (let i: number = 0; i < 6; i++) {
6 выглядит как магическое число. заведи const weekDaysCount

2019-03-24 11:02 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DatePicker/WorkDate.ts
> +  public fillWeekDays(): Date[] {
fillWeekDays -> getWeekDays

2019-03-24 11:48 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/WorkDate.ts
> +  public fillWeekDays(): Date[] {
сделал

2019-03-24 11:48 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/WorkDate.ts
> +    for (let i: number = 0; i < 6; i++) {
сделал

2019-03-24 11:48 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/WorkDate.ts
> +    for (let i: number = 0; i < 6; i++) {
только в коммитах про это написать забыл

2019-03-24 11:49 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/WorkDate.ts
> +  public getMonthString(month): string {
исправил

2019-03-24 11:49 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/WorkDate.ts
> +  public weekDayString(dayInWeek): string {
исправил

2019-03-24 11:49 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/app.module.ts
> +      { path: 'dish-card', component: DishSimpleComponent },
да, тут была ошибка, исправил

2019-03-24 11:50 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/WorkDate.ts
> +    switch (dayInWeek) {
исправил

2019-03-24 11:50 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/WorkDate.ts
> +  public getMonthString(month): string {
сделал

2019-03-24 11:50 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +    return day == this.selectedDate ? 'selected-date' : '';
исправил

2019-03-24 11:50 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public weekDays: Date[] = this.workDate.fillWeekDays();
исправил

2019-03-24 11:50 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public workDate: WorkDate = new WorkDate();
исправил

2019-03-24 15:49 UTC, Qmannn requested changes

2019-03-24 15:49 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public monthString(numMonth: number): string {
Входной параметр должен быть типа MonthNumber вместо number

2019-03-24 15:49 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public weekDayString(numWeekDay: number): string {
Так же типа нужно сделать WeekDayNumber

2019-03-24 15:49 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DatePicker/Enums/MonthNumber.ts
> +export enum MonthNumber {
Енумы в отдельную папку выносить не нужно, расположи в той же папке где лежит компонент

2019-03-24 15:54 UTC, Qmannn requested changes

2019-03-24 15:54 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DatePicker/WorkDate.ts
> +      const weekDay: Date = this.addDay(now, i);
Неделя сейчас начинается с воскресенья, нужно чтобы с понедельника начиналась

2019-03-24 15:58 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/WorkDate.ts
> +      const weekDay: Date = this.addDay(now, i);
мне значит нужно написать условие? тип если у нас воскресенье, то начинать с понедельника? или вообще следует сделать условие, чтобы воскресенья не было?

2019-03-24 16:02 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DatePicker/WorkDate.ts
> +      const weekDay: Date = this.addDay(now, i);
В общем, нужно чтобы дата всегда начиналась с понедельника: рабочая неделя. Допустим сегодня четверг 4 число, значит должна быть отображена неделя с понедельника 1 числа до субботы 6 числа, а выделанная дата должны быть текущей

2019-03-24 16:04 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/WorkDate.ts
> +      const weekDay: Date = this.addDay(now, i);
я понял, просто мне сначала по другому объяснили, что наша дата сегодняшняя должна быть первой

2019-03-25 15:01 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/WorkDate.ts
> +      const weekDay: Date = this.addDay(now, i);
сделал функцию сравнения дат

2019-03-25 15:01 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public weekDayString(numWeekDay: number): string {
исправил

2019-03-25 15:01 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public monthString(numMonth: number): string {
исправил

2019-03-26 15:45 UTC, Qmannn requested changes

2019-03-26 15:45 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DatePicker/DateHelper.ts
> +  public getWeekDays(): Date[] {
Будет лучше если в параметры этого метода передавать Date тогда метод станет универсальным и позволит строить неделю не только для текущей даты, но и для любой другой.
По факту нужно заменить now на параметр функции.

2019-03-26 19:19 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/DateHelper.ts
> +  public getWeekDays(): Date[] {
сделал

2019-03-26 19:58 UTC, Qmannn approved these changes

2019-03-31 08:15 UTC, Qmannn approved these changes

2019-03-31 14:21 UTC, merged