Issue 68 editing menu
Qmannn/food-service pull request #71
Opened 2019-03-18 15:31 UTC by glcherepanov

2019-03-24 11:16 UTC, Qmannn requested changes

2019-03-24 11:16 UTC, Qmannn commented on FoodAdmin/ClientApp/src/components/pages/EditMenu/EditMenu.Component.html
> +                            <th>{{dish.name}}</th>
Давай добавим еще одну колонку "Тип блюда"
У нас в файле DishList.Component.ts есть функция getDishCategory, ее можно переиспользовать.
1) Создать в папке Src папку Services
2)  там добавить класс DishTypeNameResolver 
3) перенести туда метод getDishCategory
4) Зиспользовать его в этом компоненте и в компоненте DishListComponent

2019-03-25 15:04 UTC, glcherepanov commented on FoodAdmin/ClientApp/src/components/pages/EditMenu/EditMenu.Component.html
> +                            <th>{{dish.name}}</th>
сделал

2019-03-26 20:02 UTC, Qmannn approved these changes
Можно сливать и закрыть задачу.
При слияниии нужно выбрать SquashAndMerge

2019-03-27 12:07 UTC, merged