ISSUE-70 add select users and get order
Qmannn/food-service pull request #73
Opened 2019-03-30 15:56 UTC by ondrosru

2019-03-31 09:52 UTC, Qmannn requested changes

2019-03-31 09:52 UTC, Qmannn commented on FoodService/ClientApp/src/HttpServices/HttpService.ts
> +    public delete<T, comamndId>(url: string, params?: HttpParams): Observable<T> {
Этот метод надо удалить

2019-03-31 09:52 UTC, Qmannn commented on FoodService/ClientApp/src/HttpServices/HttpService.ts
> +import { Observable } from 'rxjs/Observable';
Импорт надо удалить. Если нужен Observable - он должн браться из '@angular/core';

2019-03-31 09:52 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/Pages/OrderPage/OrderPage.Component.html
> +                <option *ngFor="let user of users">{{user.name}}</option>
Надо бы добавить ngModel для селекта, чтобы выбранный пользователь сохранялся в свойстве компонента

```
            <select class="form-control" [(ngModel)]="selectedUserId">
                <option *ngFor="let user of users" [ngValue]="user.userId">{{user.name}}</option>
            </select>
```

2019-03-31 09:52 UTC, Qmannn commented on FoodService/Dto/User/UserDto.cs
> +        public int UserId { get; set; }
Можно назвать просто Id

2019-04-01 14:17 UTC, ondrosru commented on FoodService/ClientApp/src/HttpServices/HttpService.ts
> +    public delete<T, comamndId>(url: string, params?: HttpParams): Observable<T> {
удалил

2019-04-01 14:17 UTC, ondrosru commented on FoodService/ClientApp/src/app/Components/Pages/OrderPage/OrderPage.Component.html
> +                <option *ngFor="let user of users">{{user.name}}</option>
изменил

2019-04-01 14:17 UTC, ondrosru commented on FoodService/Dto/User/UserDto.cs
> +        public int UserId { get; set; }
изменил

2019-04-01 14:44 UTC, ondrosru commented on FoodService/ClientApp/src/HttpServices/HttpService.ts
> +import { Observable } from 'rxjs/Observable';
Он нужен

2019-04-01 14:50 UTC, Qmannn approved these changes

2019-04-01 15:08 UTC, merged