issue-79 Добавлено получение списка меню при клике на дату
Qmannn/food-service pull request #82
Opened 2019-04-07 13:52 UTC by ondrosru

2019-04-07 14:17 UTC, Qmannn requested changes

2019-04-07 14:17 UTC, Qmannn commented on FoodService/ClientApp/src/HttpServices/DishDataService.ts
> +export class DishDataService {
Давай сделаем этот сервис OrderDataService

2019-04-07 14:17 UTC, Qmannn commented on FoodService/ClientApp/src/HttpServices/DishDataService.ts
> +  public getDishes(): Observable<DishDto[]> {
1) Метод должен возвращать не только список блюд, но и идентификатор меню, к которому этот список привязан
2) метод должен принимать дату, на которую необходимо вернуть меню

Возвращать с бекенда можно например DayMenuDto, где одним свойством будет List<DishDto> а вторым MenuDto который будет содержать MenuId и Date

2019-04-10 13:54 UTC, Qmannn approved these changes

2019-04-11 18:02 UTC, ondrosru commented on FoodService/ClientApp/src/HttpServices/DishDataService.ts
> +export class DishDataService {
сделано

2019-04-11 18:02 UTC, ondrosru commented on FoodService/ClientApp/src/HttpServices/DishDataService.ts
> +  public getDishes(): Observable<DishDto[]> {
сделано

2019-04-11 18:32 UTC, Qmannn approved these changes

2019-04-11 18:43 UTC, merged