Добавление кнопки заказать и отправку заказа
Qmannn/food-service pull request #92
Opened 2019-04-21 16:43 UTC by ondrosru

2019-04-28 12:56 UTC, Qmannn requested changes

2019-04-28 12:56 UTC, Qmannn commented on FoodService/ClientApp/src/HttpServices/OrderDataService.ts
> +  public SendAnOrder(order: OrderDto): Observable<OrderDto> {
makeOrder думаю название больше бы подошло

2019-04-28 12:56 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/Pages/OrderPage/OrderPage.Component.ts
> +  protected sendAnOrder(): void {
makeOrder

2019-04-28 12:59 UTC, Qmannn requested changes

2019-04-28 12:59 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/Pages/OrderPage/OrderPage.Component.ts
> +    order.deliveryDate =  this.selectedDay;
Давай не будем передавать дату на которую делается заказ, а вместо этого передим идентификатор меню, а потом на бекенде сможем обпределить на какую дату делается заказ т.к. меню к дате у нас привязано. таким образом проблема с передачей времени решится на какое-то время.

2019-04-28 13:56 UTC, ondrosru commented on FoodService/ClientApp/src/app/Components/Pages/OrderPage/OrderPage.Component.ts
> +    order.deliveryDate =  this.selectedDay;
сделал

2019-04-28 13:57 UTC, ondrosru commented on FoodService/ClientApp/src/HttpServices/OrderDataService.ts
> +  public SendAnOrder(order: OrderDto): Observable<OrderDto> {
сделал

2019-04-28 14:05 UTC, ondrosru commented on FoodService/ClientApp/src/app/Components/Pages/OrderPage/OrderPage.Component.ts
> +  protected sendAnOrder(): void {
переименованно

2019-04-29 20:49 UTC, Qmannn requested changes

2019-04-29 20:49 UTC, Qmannn commented on FoodService/ClientApp/src/HttpServices/OrderDataService.ts
> +  public MakeOrder(order: OrderDto): Observable<OrderDto> {
названия методов в ts надо бы с маленькой буквы писать

2019-04-29 20:49 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/Pages/OrderPage/OrderPage.Component.html
> +        <button type="button" class="btn" (click)="MakeOrder()">Заказать</button>
MakeOrder - с маленькой буквы

2019-04-29 20:49 UTC, Qmannn commented on FoodService/Controllers/OrderController.cs
> +        [HttpPost("send-an-order")]
тут тоже название надо поправить на make-order

Строчкой ниже тоже

2019-04-30 03:52 UTC, ondrosru commented on FoodService/ClientApp/src/HttpServices/OrderDataService.ts
> +  public MakeOrder(order: OrderDto): Observable<OrderDto> {
поменял

2019-04-30 03:52 UTC, ondrosru commented on FoodService/ClientApp/src/app/Components/Pages/OrderPage/OrderPage.Component.html
> +        <button type="button" class="btn" (click)="MakeOrder()">Заказать</button>
поменял

2019-04-30 03:52 UTC, ondrosru commented on FoodService/Controllers/OrderController.cs
> +        [HttpPost("send-an-order")]
поменял

2019-04-30 05:32 UTC, Qmannn approved these changes

2019-04-30 05:54 UTC, merged