Issue 65 присоединяю список блюд к меню
Qmannn/food-service pull request #94
Opened 2019-04-29 12:57 UTC by AnastasiaBastrakova

2019-04-29 21:00 UTC, Qmannn requested changes

2019-04-29 21:00 UTC, Qmannn commented on FoodAdmin/ClientApp/src/components/pages/EditMenu/EditMenu.Component.ts
> +        this.dishes = values;
Закомментированный код думаю можно удалить

2019-04-29 21:00 UTC, Qmannn commented on FoodAdmin/ClientApp/src/components/pages/EditMenu/EditMenu.Component.ts
> +    });
В одну строчку, скобочки переносить тут не нужно

2019-04-29 21:00 UTC, Qmannn commented on FoodAdmin/ClientApp/src/environments/environment.ts
> +  baseUrl: 'http://localhost:57115/'
Надо бы вернуть 55222

чтобы работало у тебя нормально - поменяй в файле launchSettings.json в проекте

2019-04-29 21:00 UTC, Qmannn commented on FoodAdmin/Controllers/MenuController.cs
> +                MenuId = savedMenuDto.MenuId,
Не совсем понятно зачем копировать MenuDto. Может просто вернуть savedMenuDto ?

2019-04-29 21:00 UTC, Qmannn commented on FoodAdmin/ClientApp/src/components/pages/EditMenu/EditMenu.Component.ts
> +    this._menuDataService.saveMenu(this.menuToEdit).subscribe(value => {
Я правильно понимаю, что блюда привязанные к меню сейчас не сохраняются? в menuToEdit этих данных нет

2019-04-30 06:29 UTC, CaptainGlobers commented
@AnastasiaBastrakova  пока не стала добавлять изменения по MenuDishRepository ?

2019-06-03 15:45 UTC, closed without merging