Стрелочки для смены недели
Qmannn/food-service pull request #95
Opened 2019-04-29 15:43 UTC by kvladiimiir

2019-04-29 20:45 UTC, Qmannn requested changes
Выглядит круто, я считаю!)

2019-04-29 20:45 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DatePicker/DateHelper.ts
> +  public offsetWeek(day: Date, isBefore: boolean): Date {
Давай метод назовем addWeek(date, weeksCount) и в нем будем прибавлять неделю (ну а если число weeksCount будет отрицательным - соответсвенно неделя будет вычитаться)

2019-04-29 20:45 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public clickArrow(isBefore: boolean): void {
Давай назовем метод как-то иначе, чтобы было понятно что он неделю переключает? Мб swichWeek?
Или можно два метода запилить nextWeek() и previousWeek() - так будет наиболее понятно. Дублирование при этом допустимое, читабельность кода в любом случае на первом месте должна быть

2019-04-30 20:37 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public clickArrow(isBefore: boolean): void {
сделал 2 функции nextWeek и prevWeek

2019-04-30 20:37 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +  public clickArrow(isBefore: boolean): void {
исправил

2019-04-30 20:38 UTC, kvladiimiir commented on FoodService/ClientApp/src/app/Components/DatePicker/DateHelper.ts
> +  public offsetWeek(day: Date, isBefore: boolean): Date {
исправил

2019-05-06 10:12 UTC, Qmannn requested changes

2019-05-06 10:12 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +import { AfterViewInit, ApplicationRef, ChangeDetectorRef, Component, EventEmitter, Output } from '@angular/core';
ChangeDetectorRef он тут нужен? Думаю можно его удалить

2019-05-06 10:12 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DatePicker/DateHelper.ts
> +    return new Date(date.getFullYear(), date.getMonth(), date.getDate() + weeksCount);
weeksCount - количсетво недель, а добавление производится к дням
Правильно будет date.getDate() + (weeksCount * 7)

2019-05-06 10:12 UTC, Qmannn commented on FoodService/ClientApp/src/app/Components/DatePicker/DatePicker.Component.ts
> +    const weeksCount: number = 7;
Количество недель должно быть 1 или -1

2019-05-24 18:34 UTC, Qmannn approved these changes

2019-05-27 09:14 UTC, merged